# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kalver\Desktop\Plugins\mailabl-qgis\mailabl-qgis\widgets\Confirmation_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 500)
        Dialog.setStyleSheet("/*üleüldine taust ja toonid*/\n"
"/*   *{ \n"
"    --gray-0: #fff;\n"
"    --gray-50: #f7f7f8;\n"
"    --gray-100: #ececf1;\n"
"    --gray-200: #d9d9e3;\n"
"    --gray-300: #c5c5d2;\n"
"    --gray-400: #acacbe;\n"
"    --gray-500: #8e8ea0;\n"
"    --gray-600: #565869;\n"
"    --gray-700: #40414f;\n"
"    --gray-800: #343541;\n"
"    --gray-900: #202123;\n"
"    gray-950: #050509\n"
"    }*/\n"
"\n"
"\n"
"\n"
"/*üleüldine taust ja toonid*/\n"
"\n"
"*{\n"
"    border: transparent;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #c5c5d2;\n"
"}\n"
"\n"
"\n"
"#Dialog{\n"
"    background-color: #202123;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    padding: 1px 8px;\n"
"    border-radius: 6px;\n"
"    background-color:#40414f;\n"
"    border: 0.5px solid #565869;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8e8ea0;\n"
"    padding: 1px 8px;\n"
"    border-radius: 8px;\n"
"    border: 0.5px solid #acacbe;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px 8px;\n"
"    border-radius: 6px\n"
"}\n"
"\n"
"\n"
"\n"
"#f_heading, #f_results, #tblW_confirmation{\n"
"\n"
"        border: 1px solid #2c313c;\n"
"        border-radius: 3px\n"
"        \n"
"    }\n"
"\n"
"\n"
"#f_buttons {\n"
"    border-top: 1px solid #2c313c; \n"
"    border-radius: 1px\n"
"}\n"
"\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainFrame = QtWidgets.QFrame(Dialog)
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.MainFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.f_heading = QtWidgets.QFrame(self.MainFrame)
        self.f_heading.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_heading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_heading.setObjectName("f_heading")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.f_heading)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_info = QtWidgets.QLabel(self.f_heading)
        self.lb_info.setObjectName("lb_info")
        self.horizontalLayout.addWidget(self.lb_info)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.f_heading)
        self.f_results = QtWidgets.QFrame(self.MainFrame)
        self.f_results.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_results.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_results.setObjectName("f_results")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.f_results)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tblW_confirmation = QtWidgets.QTableWidget(self.f_results)
        self.tblW_confirmation.setObjectName("tblW_confirmation")
        self.tblW_confirmation.setColumnCount(0)
        self.tblW_confirmation.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tblW_confirmation)
        self.verticalLayout_4.addWidget(self.f_results)
        self.f_footer = QtWidgets.QFrame(self.MainFrame)
        self.f_footer.setStyleSheet("")
        self.f_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_footer.setObjectName("f_footer")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.f_footer)
        self.verticalLayout_8.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_5 = QtWidgets.QFrame(self.f_footer)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lb_results = QtWidgets.QLabel(self.frame_5)
        self.lb_results.setObjectName("lb_results")
        self.horizontalLayout_4.addWidget(self.lb_results)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.f_footer)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lbl_Total_toAdd = QtWidgets.QLabel(self.frame_6)
        self.lbl_Total_toAdd.setObjectName("lbl_Total_toAdd")
        self.horizontalLayout_5.addWidget(self.lbl_Total_toAdd)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.verticalLayout_4.addWidget(self.f_footer)
        self.verticalLayout.addWidget(self.MainFrame)
        self.f_buttons = QtWidgets.QFrame(Dialog)
        self.f_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_buttons.setObjectName("f_buttons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.f_buttons)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.f_buttons)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.f_buttons, 0, QtCore.Qt.AlignBottom)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb_info.setText(_translate("Dialog", "Allolevad kinnistud juba on Mailablis ja neid uuesti ei lisata"))
        self.label_4.setText(_translate("Dialog", "Valikust eelnevalt Mailablis:"))
        self.lb_results.setText(_translate("Dialog", "TextLabel"))
        self.label_5.setText(_translate("Dialog", "Lisatakse:"))
        self.lbl_Total_toAdd.setText(_translate("Dialog", "TextLabel"))
