# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kalver\Desktop\Plugins\mailabl-qgis\mailabl-qgis\widgets\Properties_connector_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1018, 607)
        Dialog.setStyleSheet("*{\n"
"    border: transparent;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #c5c5d2;\n"
"}\n"
"\n"
"/*konteinerite peamised omadused*/\n"
"\n"
"QDialog{\n"
"    background-color: #272c35;\n"
"}\n"
"\n"
"#swWorkSpace{\n"
"    background-color: #202123;\n"
"}\n"
"#Sevituudid{\n"
"    background-color: #343b47;\n"
"}\n"
"\n"
"#leftMenuContainer{\n"
"    background-color: #202123 ;\n"
"}\n"
"\n"
"#rightMenuContainer{\n"
"    background-color: #272c35;\n"
"}\n"
"\n"
"\n"
"/*nuppu peamised omadused*/\n"
"/*Üldomadused*/\n"
"QPushButton{\n"
"    padding: 1px 8px;\n"
"    border-radius: 6px;\n"
"    background-color:#40414f;\n"
"    border: 0.5px solid #565869;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8e8ea0;\n"
"    padding: 1px 8px;\n"
"    border-radius: 8px;\n"
"    border: 0.5px solid #acacbe;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frHeading = QtWidgets.QFrame(self.frame_3)
        self.frHeading.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frHeading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frHeading.setObjectName("frHeading")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frHeading)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frHeading)
        self.frame.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblDescription = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblDescription.setFont(font)
        self.lblDescription.setObjectName("lblDescription")
        self.horizontalLayout_3.addWidget(self.lblDescription)
        self.lblElementName = QtWidgets.QLabel(self.frame)
        self.lblElementName.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblElementName.setFont(font)
        self.lblElementName.setText("")
        self.lblElementName.setObjectName("lblElementName")
        self.horizontalLayout_3.addWidget(self.lblElementName)
        self.lblElementNumber = QtWidgets.QLabel(self.frame)
        self.lblElementNumber.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblElementNumber.setFont(font)
        self.lblElementNumber.setText("")
        self.lblElementNumber.setObjectName("lblElementNumber")
        self.horizontalLayout_3.addWidget(self.lblElementNumber)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame)
        self.label = QtWidgets.QLabel(self.frHeading)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frHeading)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout_4.addWidget(self.frHeading)
        self.pbClear_list = QtWidgets.QPushButton(self.frame_3)
        self.pbClear_list.setObjectName("pbClear_list")
        self.verticalLayout_4.addWidget(self.pbClear_list, 0, QtCore.Qt.AlignLeft)
        self.frTable = QtWidgets.QFrame(self.frame_3)
        self.frTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTable.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frTable.setObjectName("frTable")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frTable)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tvProperties = QtWidgets.QTableView(self.frTable)
        self.tvProperties.setObjectName("tvProperties")
        self.horizontalLayout.addWidget(self.tvProperties)
        self.verticalLayout_4.addWidget(self.frTable)
        self.fButtons = QtWidgets.QFrame(self.frame_3)
        self.fButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fButtons.setObjectName("fButtons")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.fButtons)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(411, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pbCancel = QtWidgets.QPushButton(self.fButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\widgets\\../Functions/icons/Icons_hele/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbCancel.setIcon(icon)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_7.addWidget(self.pbCancel)
        self.pbSave = QtWidgets.QPushButton(self.fButtons)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pbSave.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\widgets\\../Functions/icons/Icons_hele/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSave.setIcon(icon1)
        self.pbSave.setIconSize(QtCore.QSize(16, 16))
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_7.addWidget(self.pbSave)
        self.verticalLayout_4.addWidget(self.fButtons)
        self.frFooter = QtWidgets.QFrame(self.frame_3)
        self.frFooter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frFooter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frFooter.setObjectName("frFooter")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frFooter)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4.addWidget(self.frFooter)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.fHelpMenu = QtWidgets.QFrame(self.frame_2)
        self.fHelpMenu.setMinimumSize(QtCore.QSize(200, 0))
        self.fHelpMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fHelpMenu.setStyleSheet("")
        self.fHelpMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fHelpMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fHelpMenu.setObjectName("fHelpMenu")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.fHelpMenu)
        self.verticalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.fHelpMenu)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.fHelpMenu)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_10.addWidget(self.textEdit)
        self.horizontalLayout_2.addWidget(self.fHelpMenu)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblDescription.setText(_translate("Dialog", "Objekti nimetus:"))
        self.label.setText(_translate("Dialog", "Alusta kaardil kinnistute lisamist."))
        self.label_2.setText(_translate("Dialog", "NB! Tabelis kuvatakse hetkel kaardil valitud kinnistud."))
        self.pbClear_list.setText(_translate("Dialog", "Alusta valimist uuesti"))
        self.pbCancel.setText(_translate("Dialog", "Tühista"))
        self.pbSave.setText(_translate("Dialog", "Salvesta"))
        self.label_4.setText(_translate("Dialog", "Kuidas tööriista\n"
"kasutada?\n"
"(juhend koostamisel)"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Juhend koostamisel</p></body></html>"))
