# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kalver\Desktop\Plugins\mailabl-qgis\mailabl-qgis\Functions\EVEL\widgets\EVEL.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EVEL(object):
    def setupUi(self, EVEL):
        EVEL.setObjectName("EVEL")
        EVEL.resize(900, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EVEL.sizePolicy().hasHeightForWidth())
        EVEL.setSizePolicy(sizePolicy)
        EVEL.setMinimumSize(QtCore.QSize(900, 750))
        EVEL.setMaximumSize(QtCore.QSize(900, 750))
        EVEL.setStyleSheet("\n"
"*{\n"
"    border: transparent;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #c5c5d2;\n"
"}\n"
"\n"
"\n"
"QWidget{\n"
"    background-color: #272c35;\n"
"    color:#c5c5d2\n"
"}\n"
"\n"
"\n"
"/*Line Edit styling*/\n"
"QLineEdit {\n"
"    background-color: #35363f;  /* Lighter background color */\n"
"    color: #ececf1;\n"
"    /*border: 1px solid #4d4d5b;  Thinner border with a different color */\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #3d3e47;  /* Slightly darker background color on hover */\n"
"}\n"
"\n"
"/* Remove top and side borders */\n"
"QLineEdit {\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"\n"
"/*konteinerite peamised omadused*/\n"
"#centerMenuSubContainer{\n"
"    background-color: #272c35;\n"
"}\n"
"\n"
"#swWorkSpace{\n"
"    background-color: #202123;\n"
"}\n"
"#Sevituudid{\n"
"    background-color: #343b47;\n"
"}\n"
"\n"
"#leftMenuContainer{\n"
"    background-color: #202123 ;\n"
"}\n"
"\n"
"#rightMenuContainer{\n"
"    background-color: #272c35;\n"
"}\n"
"\n"
"#SetupLayers, #SetupLayers_2, #SetupUserData {\n"
"border: none;\n"
"border-bottom: 1px solid rgb(131, 142, 162);\n"
"}\n"
"\n"
"/*nuppu peamised omadused*/\n"
"/*Üldomadused*/\n"
"QPushButton{\n"
"    padding: 1px 5px;\n"
"    text-align: center;\n"
"    border-radius: 5px;\n"
"    background-color:#40414f;\n"
"    border: 1px solid #565869;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8e8ea0;\n"
"    border: 0.5px solid #acacbe;\n"
"    color: #343541;\n"
"    text-align: center;\n"
"    padding: 2px 5px;\n"
"    border-radius: 5px;    \n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #303040; /* Adjusted disabled background color */\n"
"    border: 1px solid #707070; /* Adjust border color for disabled state */\n"
"    color: #8a95a5; /* Adjust text color for disabled state */\n"
"}\n"
"\n"
"\n"
"#UC_Main_Frame QPushButton,#pbChoose_Properties_for_Projects{\n"
"    padding: 1px 8px;\n"
"    border-radiusr: 6px;\n"
"}\n"
"\n"
"#UC_Main_Frame QPushButton:hover{\n"
"\n"
"    padding: 1px 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"#wOl_Settings QPushButton{\n"
"    padding: 1px 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#wOl_Settings QPushButton:hover{\n"
"    padding: 1px 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#rightMenuContainer QPushButton{\n"
"    text-align: right;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    \n"
"}\n"
"\n"
"#rightMenuContainer QPushButton:hover{\n"
"    text-align: right;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;  \n"
"}\n"
"\n"
"\n"
"#leftMenuContainer QPushButton{\n"
"    text-align: left;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;    \n"
"}\n"
"#leftMenuContainer QPushButton:hover{\n"
"    text-align: left;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* Combined Style for QComboBox to Ensure Consistency */\n"
"\n"
"/* Base style for QComboBox */\n"
"QComboBox {\n"
"    border: 1px solid #565869; /* Using --gray-600 */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    background-color: #343541; /* Using --gray-800 */\n"
"    color: #ececf1; /* Using --gray-100 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QComboBox:disabled {\n"
"    background-color: #c5c5d2; /* Using --gray-300 */\n"
"    color: #8e8ea0; /* Using --gray-500 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Hover state */\n"
"QComboBox:hover {\n"
"    border: 1px solid #acacbe; /* Using --gray-400 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Focus state */\n"
"QComboBox:focus {\n"
"    border: 1px solid #acacbe; /* Kept original lime green color */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Dropdown button */\n"
"QComboBox::drop-down {\n"
"    subcontrol-position: center right;\n"
"    border-radius: 3px; /* Rounded corners */\n"
"    /*width: 24px;*/\n"
"    borde: 0.5px solid #acacbe; /* Kept original lime green color */\n"
"    background-color: #343541; /* Using --gray-800 */\n"
"}\n"
"\n"
"/* Dropdown arrow */\n"
"QComboBox::down-arrow {\n"
"    image: url(\':/qt-project.org/styles/macstyle/images/toolbar-ext.png\'); /* Default arrow image */\n"
"    height: 16px;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(\':/qt-project.org/styles/macstyle/images/toolbar-ext.png\'); /* Arrow image on hover, focus */\n"
"}\n"
"\n"
"/* QAbstractItemView (dropdown list) */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #343541; /* Using --gray-900 */\n"
"    border: 1px solid #4d4d4d; /* Similar to gray-600 */\n"
"    selection-background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgba(50, 50, 50, 255), /* Dark gray */\n"
"        stop: 1 rgba(100, 100, 100, 255) /* Lighter gray */\n"
"    );\n"
"    selection-color: #ececf1; /* Using --gray-100 */\n"
"    color: #ececf1;\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Selected item in list */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgba(50, 50, 50, 255), /* Dark gray */\n"
"        stop: 1 rgba(100, 100, 100, 255) /* Lighter gray */\n"
"    );\n"
"    color: #ececf1; /* Using --gray-100 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Hover over item in list */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgba(50, 50, 50, 255), /* Dark gray */\n"
"        stop: 1 rgba(100, 100, 100, 255) /* Lighter gray */\n"
"    );\n"
"    color: #ececf1; /* Using --gray-100 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Handle the padding of items in the list view */\n"
"QComboBox QAbstractItemView::item {\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Ensure keyboard navigation shows selection */\n"
"QComboBox::item:selected:!hover {\n"
"    background-color: qlineargradient(\n"
"        spread: pad, \n"
"        x1: 0, y1: 0, \n"
"        x2: 0, y2: 1, \n"
"        stop: 0.259887 rgba(50, 50, 50, 202), \n"
"        stop: 1 rgba(180, 180, 180, 255)\n"
"    ); \n"
"    color: #ececf1; /* White text color for keyboard selection */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Checked state of the checkbox */\n"
"QComboBox::indicator:checked {\n"
"    background-color: #565869; /* Kept original lime green color */\n"
"    image: url(\':/images/themes/default/algorithms/mAlgorithmCheckGeometry.svg\'); /* Path to your checked image */\n"
"    width: 10px;  /* Adjusted width to fit within the border */\n"
"    height: 10px; /* Adjusted height to fit within the border */\n"
"}\n"
"\n"
"/* Unchecked state can have a background color */\n"
"QComboBox::indicator:unchecked {\n"
"    background-color: #565869; /* Using --gray-600 */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* General QCheckBox styles */\n"
"QCheckBox {\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"    spacing: 5px; /* Space between checkbox and text */\n"
"}\n"
"\n"
"/* Style the indicator (checkbox) */\n"
"QCheckBox::indicator {\n"
"    width: 12px; /* Width of the checkbox */\n"
"    height: 12px; /* Height of the checkbox */\n"
"    background-color: #3a3b46; /* Darker gray for unchecked state */\n"
"    border: 1px solid #565869; /* Border color for unchecked state */\n"
"    border-radius: 2px; /* Slightly rounded corners */\n"
"}\n"
"\n"
"/* Style the indicator when checked */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #4a4b59; /* Slightly darker gray for checked state */\n"
"    border: 1px solid #4d4d4d; /* Border color matching the theme */\n"
"    border-radius: 2px; /* Slightly rounded corners */\n"
"    image: url(:/images/themes/default/algorithms/mAlgorithmCheckGeometry.svg); /* Using provided SVG icon URL */\n"
"}\n"
"\n"
"/* Style the indicator when unchecked */\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: #3a3b46; /* Darker gray for unchecked state */\n"
"    border: 1px solid #565869; /* Border color for unchecked state */\n"
"}\n"
"\n"
"/* Style the indicator when hovered */\n"
"QCheckBox::indicator:hover {\n"
"    background-color: #4e4f5b; /* Medium gray when hovering */\n"
"}\n"
"\n"
"/* Style the indicator when disabled */\n"
"QCheckBox::indicator:disabled {\n"
"    background-color: #30303a; /* Darker background color for disabled state */\n"
"    border: 1px solid #4d4d4d; /* Darker border for disabled state */\n"
"}\n"
"\n"
"/* Style the indicator when checked and disabled */\n"
"QCheckBox::indicator:checked:disabled {\n"
"    background-color: rgba(50, 50, 60, 0.5); /* Semi-transparent darker gray for checked and disabled state */\n"
"    border: 1px solid #4d4d4d; /* Border color matching the theme */\n"
"    image: url(:/images/themes/default/algorithms/mAlgorithmCheckGeometry.svg); /* Using provided SVG icon URL */\n"
"    opacity: 0.5; /* Make the icon appear disabled */\n"
"}\n"
"\n"
"/* Style the checkbox text when disabled */\n"
"QCheckBox:disabled {\n"
"    color: #6a6a75; /* Darker text color for disabled state */\n"
"}\n"
"\n"
"\n"
"QGroupBox{\n"
"    color: #ececf1;\n"
"}\n"
"\n"
"\n"
"/* Style for the selected tab */\n"
"QTabBar::tab:selected {\n"
"    background-color: #50515f; /* Background color for the selected tab */\n"
"    color: #ececf1; /* Text color for the selected tab */\n"
"    border: 1px solid #acacbe; /* Lighter border for the selected tab */\n"
"    border-bottom: 1px solid #202123; /* Match the background color of the tab pane to create a seamless look */\n"
"    padding: 7px 12px; /* Slightly adjust padding for selected tab */\n"
"}\n"
"\n"
"/* Style for the hovered tab */\n"
"QTabBar::tab:hover {\n"
"    background-color: #8e8ea0; /* Background color when hovering over a tab */\n"
"    color: #343541; /* Text color for the hovered tab */\n"
"    border: 1px solid #acacbe; /* Lighter border on hover */\n"
"}\n"
"\n"
"/* Style for disabled tabs */\n"
"QTabBar::tab:disabled {\n"
"    background-color: #30303a; /* Darker background for disabled tabs */\n"
"    color: #6a6a75; /* Muted text color for disabled tabs */\n"
"    border: 1px solid #565869; /* Border color for disabled tabs */\n"
"}\n"
"\n"
"/* Adjustments to the tab pane (content area below the tabs) */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #565869; /* Border around the content area */\n"
"    background-color: #202123; /* Match the background of the content area to other containers */\n"
"    border-radius: 3px; /* Rounded corners for the content area */\n"
"    margin-top: -1px; /* Overlap with the tab bar to create a seamless transition */\n"
"}\n"
"\n"
"/* General QScrollBar style within QTableView */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: transparent; /* Ensure the scrollbar background is transparent */\n"
"}\n"
"\n"
"/* Vertical scroll bar groove (track) */\n"
"QScrollBar::groove:vertical {\n"
"    border: 1px solid #4d4d4d; /* Dark border around the groove */\n"
"    width: 8px; /* Width of the groove */\n"
"    background: #333; /* Darker gray for the groove background */\n"
"    border-radius: 3px; /* Adjusted to be less than half of 8px */\n"
"}\n"
"\n"
"/* Horizontal scroll bar groove (track) */\n"
"QScrollBar::groove:horizontal {\n"
"    border: 1px solid #4d4d4d; /* Dark border around the groove */\n"
"    height: 8px; /* Height of the groove */\n"
"    background: #333; /* Darker gray for the groove background */\n"
"    border-radius: 3px; /* Adjusted to be less than half of 8px */\n"
"}\n"
"\n"
"/* Vertical scroll bar handle (thumb) */\n"
"QScrollBar::handle:vertical {\n"
"    background: #b5b5b5; /* Lighter gray for the handle */\n"
"    border: 1px solid #707070; /* Slightly darker border for the handle */\n"
"    width: 16px; /* Width of the handle */\n"
"    border-radius: 6px; /* Adjusted to be less than half of 16px for a rounded effect */\n"
"}\n"
"\n"
"/* Horizontal scroll bar handle (thumb) */\n"
"QScrollBar::handle:horizontal {\n"
"    background: #b5b5b5; /* Lighter gray for the handle */\n"
"    border: 1px solid #707070; /* Slightly darker border for the handle */\n"
"    height: 16px; /* Height of the handle */\n"
"    border-radius: 6px; /* Adjusted to be less than half of 16px for a rounded effect */\n"
"}\n"
"\n"
"/* Handle when hovered (both vertical and horizontal) */\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background: #d8d8d8; /* Lighter gray when hovered */\n"
"}\n"
"\n"
"/* Handle when pressed (both vertical and horizontal) */\n"
"QScrollBar::handle:vertical:pressed, QScrollBar::handle:horizontal:pressed {\n"
"    background: #999; /* Darker gray when pressed */\n"
"}\n"
"\n"
"/* Slider groove when focused (both vertical and horizontal) */\n"
"QScrollBar::groove:vertical:focus, QScrollBar::groove:horizontal:focus {\n"
"    background: #444; /* Slightly brighter when focused */\n"
"}\n"
"\n"
"/* Scrollbar arrows (both vertical and horizontal) */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: #40414f; /* Background for the arrows */\n"
"    border: 1px solid #565869; /* Border for the arrows */\n"
"    border-radius: 2px; /* Adjusted to be less than half of 4px */\n"
"}\n"
"\n"
"/* Arrows on hover */\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::sub-line:vertical:hover,\n"
"QScrollBar::add-line:horizontal:hover, QScrollBar::sub-line:horizontal:hover {\n"
"    background: #8e8ea0; /* Lighter background on hover */\n"
"}\n"
"\n"
"/* Style for the scroll bar pages (scroll bar track) */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none; /* No background for the pages */\n"
"}\n"
"\n"
"/* Adjust QListWidget style */\n"
"QListWidget {\n"
"    background-color: #2e2f38; /* Dark gray background to match the new theme */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"    border: 1px solid #4d4d4d; /* Border color matching the scrollbar groove */\n"
"    border-radius: 3px; /* Rounded corners */\n"
"    padding: 3px; /* Add padding to the list */\n"
"}\n"
"\n"
"/* Style for individual items in the QListWidget */\n"
"QListWidget::item {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 rgba(60, 62, 73, 0.2), stop: 1 rgba(42, 42, 51, 0.35)); /* Gradient for non-selected items */\n"
"    color: #d1d1e0; /* Light gray text color for unselected items */\n"
"    padding: 3px; /* Padding around list items */\n"
"    border-radius: 1.5px; /* Slight rounding of the item edges */\n"
"}\n"
"\n"
"/* Style for selected items in QListWidget */\n"
"QListWidget::item:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 rgba(210, 72, 72, 0.05), stop: 1 rgba(210, 72, 72, 0.25)); /* Gradient for selected items */\n"
"    color: #ececf1; /* Lighter text color for selected items */\n"
"    border: 1px solid #707070; /* Lighter border for the selected item */\n"
"}\n"
"\n"
"/* Style for hovered items in QListWidget */\n"
"QListWidget::item:hover {\n"
"    background-color: #4e4f5b; /* Medium gray background color when hovering */\n"
"    color: #ececf1; /* Text color on hover to maintain contrast */\n"
"}\n"
"\n"
"/* Style for disabled items in QListWidget */\n"
"QListWidget::item:disabled {\n"
"    background-color: #30303a; /* Darker background for disabled items */\n"
"    color: #6a6a75; /* Muted gray text color for disabled items */\n"
"}\n"
"\n"
"/* General QLineEdit styles */\n"
"QLineEdit {\n"
"    background-color: #35363f; /* Lighter background color */\n"
"    color: #ececf1; /* Light gray text color */\n"
"    border: 1px solid #4d4d5b; /* Thinner border with a different color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 4px; /* Padding inside the line edit */\n"
"    /* Remove top and side borders */\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"/* Style for the line edit when focused */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #6a6a75; /* Highlight border color when focused */\n"
"    background-color: #35363f; /* Keep the background color consistent when focused */\n"
"}\n"
"\n"
"/* Style for the placeholder text */\n"
"QLineEdit::placeholder {\n"
"    color: #6a6a75; /* Lighter gray color for placeholder text */\n"
"}\n"
"\n"
"/* Style for the line edit when disabled */\n"
"QLineEdit:disabled {\n"
"    background-color: #30303a; /* Darker background color for disabled state */\n"
"    color: #6a6a75; /* Muted gray text color for disabled state */\n"
"    border: 1px solid #4d4d4d; /* Same border color as normal state */\n"
"}\n"
"\n"
"/* Style for the line edit when read-only */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #35363f; /* Same as normal background */\n"
"    color: #ececf1; /* Same as normal text color */\n"
"    border: 1px solid #4d4d5b; /* Same as normal border */\n"
"    border-style: dashed; /* Dashed border style for read-only state */\n"
"}\n"
"\n"
"/* Style for the line edit when active */\n"
"QLineEdit:active {\n"
"    border: 1px solid #6a6a75; /* Highlight border color when active */\n"
"}\n"
"\n"
"/* Style for the line edit when hovered */\n"
"QLineEdit:hover {\n"
"    background-color: #3d3e47; /* Slightly darker background color on hover */\n"
"}\n"
"\n"
"/* Style for the line edit when error state (optional) */\n"
"QLineEdit:invalid {\n"
"    border: 1px solid #d20000; /* Red border for invalid input */\n"
"}\n"
"\n"
"/* Style for the line edit when modified (optional) */\n"
"QLineEdit:modified {\n"
"    border: 1px solid #d1d1e0; /* Border color indicating modification */\n"
"}\n"
"\n"
"\n"
"/* General QTableView adjustments */\n"
"QTableView {\n"
"    background-color: #2e2f38; /* Dark gray for all rows */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"    border: 1px solid #4d4d4d; /* Border color matching the scrollbar groove */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    gridline-color: #565869; /* Gridline color */\n"
"    selection-background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgba(46, 47, 56, 10),   /* Lighter gray with higher transparency (about 47%) */\n"
"        stop: 1 rgba(210, 72, 72, 50)    /* Darker red with lower transparency (about 29%) */\n"
"    ); /* Gradient for selected cells */\n"
"    selection-color: #ececf1; /* Lighter text color for selected cells */\n"
"}\n"
"\n"
"/* Adjust header style */\n"
"QHeaderView::section {\n"
"    background-color: #35353f; /* Darker gray background for the header */\n"
"    color: #d1d1e0; /* Light gray text color in the header */\n"
"    border-top: 0.5px solid #323232; /* Slightly darker border on top */\n"
"    border-left: 0.5px solid #323232; /* Slightly darker border on left */\n"
"    border-right: 0.5px solid #323232; /* Slightly darker border on right */\n"
"    border-bottom: 1px solid #4d4d4d; /* Lighter bottom border to separate data from headers */\n"
"    padding: 1px 3px; /* Slightly reduced padding */\n"
"    border-top-left-radius: 2px; /* Retain rounding on the top-left corner */\n"
"    border-top-right-radius: 2px; /* Retain rounding on the top-right corner */\n"
"    border-bottom-left-radius: 0px; /* No rounding on the bottom-left corner */\n"
"    border-bottom-right-radius: 0px; /* No rounding on the bottom-right corner */\n"
"    font-size: 11px; /* Reduced font size */\n"
"}\n"
"\n"
"/* Style for hovered rows */\n"
"QTableView::item:hover {\n"
"    background-color: #4e4f5b; /* Medium gray background color when hovering over a row */\n"
"    color: #ececf1; /* Text color on hover for better contrast */\n"
"}\n"
"\n"
"/* Style for selected rows */\n"
"QTableView::item:selected {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgba(46, 47, 56, 10),   /* Lighter gray with higher transparency (about 47%) */\n"
"        stop: 1 rgba(210, 72, 72, 50)    /* Darker red with lower transparency (about 29%) */\n"
"    ); /* Gradient background color for selected rows */\n"
"    color: #ececf1; /* Light gray text color for selected rows */\n"
"}\n"
"\n"
"/* Style for all rows (non-selected) */\n"
"QTableView::item {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgba(80, 80, 80, 25),   /* Lighter gray with 20% opacity (2 steps lighter) */\n"
"        stop: 1 rgba(42, 42, 51, 255)    /* Darker gray with 35% opacity */\n"
"    ); /* Gradient background color for non-selected rows */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"}\n"
"\n"
"/* Ensure deselected rows return to their original state */\n"
"QTableView::item:!selected {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgba(80, 80, 80, 25),   /* Lighter gray with 20% opacity (2 steps lighter) */\n"
"        stop: 1 rgba(42, 42, 51, 255)    /* Darker gray with 35% opacity */\n"
"    ); /* Reset to the default background color */\n"
"    color: #d1d1e0; /* Reset to the default text color */\n"
"}\n"
"\n"
"\n"
"/* General style for QProgressBar */\n"
"QProgressBar {\n"
"    background-color: #2e2f38; /* Dark gray background matching the table */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"    border: 1px solid #4d4d4d; /* Border matching the table border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    text-align: center; /* Center the text inside the progress bar */\n"
"    padding: 2px; /* Padding for better spacing */\n"
"}\n"
"\n"
"/* Style for the progress chunk */\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #d14848, /* Start with darker red matching the selection color */\n"
"        stop: 1 #e57373  /* End with a slightly lighter red */\n"
"    ); /* Gradient effect for the progress bar */\n"
"    border-radius: 3px; /* Slight rounding of the progress chunk */\n"
"}\n"
"\n"
"/* Style for the indeterminate progress bar (if used) */\n"
"QProgressBar[minimum=\"0\"][maximum=\"0\"] {\n"
"    background-color: #2e2f38; /* Dark gray background matching the table */\n"
"    border: 1px solid #4d4d4d; /* Border matching the table border */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"}\n"
"\n"
"QProgressBar[minimum=\"0\"][maximum=\"0\"]::chunk {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #d14848, /* Start with darker red */\n"
"        stop: 1 #e57373  /* End with a slightly lighter red */\n"
"    ); /* Moving gradient for the indeterminate progress bar */\n"
"}\n"
"\n"
"/* General QGroupBox Styling */\n"
"QGroupBox {\n"
"    color: #ececf1; /* Light gray text color for the group box title */\n"
"    background-color: #272c35; /* Dark background to match the surrounding theme */\n"
"    border: 1px solid #565869; /* Border color to distinguish the group box */\n"
"    border-radius: 5px; /* Rounded corners for a smoother look */\n"
"    margin-top: 10px; /* Space above the group box title */\n"
"    padding: 10px; /* Padding inside the group box to space out contents */\n"
"}\n"
"\n"
"/* Title of the QGroupBox */\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin; /* Align the title relative to the group box\'s margin */\n"
"    subcontrol-position: top left; /* Position the title at the top left */\n"
"    padding-left: 5px; /* Add padding to the left of the title */\n"
"    padding-right: 5px; /* Add padding to the right of the title */\n"
"    background-color: #343b47; /* Background for the title to make it stand out */\n"
"    color: #ececf1; /* Text color for the title */\n"
"    border-radius: 3px; /* Slightly round the corners of the title background */\n"
"    font-weight: bold; /* Make the title text bold */\n"
"}\n"
"\n"
"/* QGroupBox when hovered */\n"
"QGroupBox:hover {\n"
"    border: 1px solid #8e8ea0; /* Lighter border color on hover */\n"
"}\n"
"\n"
"/* QGroupBox when focused */\n"
"QGroupBox:focus {\n"
"    border: 1px solid #acacbe; /* Even lighter border color when focused */\n"
"    box-shadow: 0 0 5px 1px #8e8ea0; /* Add a subtle shadow to indicate focus */\n"
"}\n"
"\n"
"/* Disabled QGroupBox */\n"
"QGroupBox:disabled {\n"
"    color: #6a6a75; /* Darker gray text color when disabled */\n"
"    background-color: #30303a; /* Slightly darker background for disabled state */\n"
"    border: 1px solid #4d4d4d; /* Darker border color for disabled state */\n"
"}\n"
"\n"
"QGroupBox::title:disabled {\n"
"    color: #6a6a75; /* Darker title text color when disabled */\n"
"    background-color: #3a3b46; /* Darker title background color for disabled state */\n"
"}\n"
"\n"
"/* Content inside the QGroupBox */\n"
"QGroupBox QWidget {\n"
"    background-color: #2e2f38; /* Match background of content to group box */\n"
"    color: #d1d1e0; /* Light gray text color for contents */\n"
"}\n"
"")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(EVEL)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fMain = QtWidgets.QFrame(EVEL)
        self.fMain.setMinimumSize(QtCore.QSize(0, 200))
        self.fMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fMain.setObjectName("fMain")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fMain)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fMainTools = QtWidgets.QFrame(self.fMain)
        self.fMainTools.setStyleSheet("")
        self.fMainTools.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fMainTools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fMainTools.setObjectName("fMainTools")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fMainTools)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.fMainTools)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cbFlowMeter = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbFlowMeter.setObjectName("cbFlowMeter")
        self.verticalLayout_6.addWidget(self.cbFlowMeter)
        self.cbCustomer = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbCustomer.setObjectName("cbCustomer")
        self.verticalLayout_6.addWidget(self.cbCustomer)
        self.cbDemarcationPoint = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbDemarcationPoint.setObjectName("cbDemarcationPoint")
        self.verticalLayout_6.addWidget(self.cbDemarcationPoint)
        self.cbApartment = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbApartment.setObjectName("cbApartment")
        self.verticalLayout_6.addWidget(self.cbApartment)
        self.cbConnectionPoints = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbConnectionPoints.setFont(font)
        self.cbConnectionPoints.setObjectName("cbConnectionPoints")
        self.verticalLayout_6.addWidget(self.cbConnectionPoints)
        self.cbEasements = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbEasements.setFont(font)
        self.cbEasements.setObjectName("cbEasements")
        self.verticalLayout_6.addWidget(self.cbEasements)
        self.cbContract = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbContract.setObjectName("cbContract")
        self.verticalLayout_6.addWidget(self.cbContract)
        self.cbProperties = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbProperties.setObjectName("cbProperties")
        self.verticalLayout_6.addWidget(self.cbProperties)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.cbWater = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbWater.setFont(font)
        self.cbWater.setObjectName("cbWater")
        self.verticalLayout_11.addWidget(self.cbWater)
        self.cbFirePlug = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbFirePlug.setObjectName("cbFirePlug")
        self.verticalLayout_11.addWidget(self.cbFirePlug)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.horizontalLayout_6.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cbRainwater = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbRainwater.setFont(font)
        self.cbRainwater.setObjectName("cbRainwater")
        self.verticalLayout_8.addWidget(self.cbRainwater)
        self.cbSewage = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbSewage.setFont(font)
        self.cbSewage.setObjectName("cbSewage")
        self.verticalLayout_8.addWidget(self.cbSewage)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_6.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cbSNConstant = QtWidgets.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbSNConstant.setFont(font)
        self.cbSNConstant.setObjectName("cbSNConstant")
        self.verticalLayout_7.addWidget(self.cbSNConstant)
        self.cbProgram = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbProgram.setObjectName("cbProgram")
        self.verticalLayout_7.addWidget(self.cbProgram)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_6.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cbPumpstation = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbPumpstation.setFont(font)
        self.cbPumpstation.setObjectName("cbPumpstation")
        self.verticalLayout_9.addWidget(self.cbPumpstation)
        self.cbSewTreatment = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbSewTreatment.setFont(font)
        self.cbSewTreatment.setObjectName("cbSewTreatment")
        self.verticalLayout_9.addWidget(self.cbSewTreatment)
        self.cbPressureStation = QtWidgets.QCheckBox(self.groupBox_8)
        self.cbPressureStation.setObjectName("cbPressureStation")
        self.verticalLayout_9.addWidget(self.cbPressureStation)
        self.cbDevice = QtWidgets.QCheckBox(self.groupBox_8)
        self.cbDevice.setObjectName("cbDevice")
        self.verticalLayout_9.addWidget(self.cbDevice)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_6.addWidget(self.groupBox_8)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.fMainTools)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbServices = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbServices.setFont(font)
        self.cbServices.setObjectName("cbServices")
        self.verticalLayout_2.addWidget(self.cbServices)
        self.cbExternalDoc = QtWidgets.QCheckBox(self.groupBox)
        self.cbExternalDoc.setObjectName("cbExternalDoc")
        self.verticalLayout_2.addWidget(self.cbExternalDoc)
        self.cbManhole = QtWidgets.QCheckBox(self.groupBox)
        self.cbManhole.setObjectName("cbManhole")
        self.verticalLayout_2.addWidget(self.cbManhole)
        self.cbValve = QtWidgets.QCheckBox(self.groupBox)
        self.cbValve.setObjectName("cbValve")
        self.verticalLayout_2.addWidget(self.cbValve)
        self.cbOperation = QtWidgets.QCheckBox(self.groupBox)
        self.cbOperation.setObjectName("cbOperation")
        self.verticalLayout_2.addWidget(self.cbOperation)
        self.cbError = QtWidgets.QCheckBox(self.groupBox)
        self.cbError.setObjectName("cbError")
        self.verticalLayout_2.addWidget(self.cbError)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbGepackage = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbGepackage.setFont(font)
        self.cbGepackage.setObjectName("cbGepackage")
        self.verticalLayout_4.addWidget(self.cbGepackage)
        self.cbSQLDatabase = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbSQLDatabase.setFont(font)
        self.cbSQLDatabase.setObjectName("cbSQLDatabase")
        self.verticalLayout_4.addWidget(self.cbSQLDatabase)
        self.cbPostgreDatabase = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbPostgreDatabase.setFont(font)
        self.cbPostgreDatabase.setObjectName("cbPostgreDatabase")
        self.verticalLayout_4.addWidget(self.cbPostgreDatabase)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.frame_5)
        self.fEVEL_settings = QtWidgets.QFrame(self.fMainTools)
        self.fEVEL_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fEVEL_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fEVEL_settings.setObjectName("fEVEL_settings")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fEVEL_settings)
        self.horizontalLayout_2.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.fEVEL_settings)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.leDatabaseName = QtWidgets.QLineEdit(self.frame_3)
        self.leDatabaseName.setObjectName("leDatabaseName")
        self.horizontalLayout_5.addWidget(self.leDatabaseName)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.leLocation = QtWidgets.QLineEdit(self.frame_2)
        self.leLocation.setObjectName("leLocation")
        self.horizontalLayout_4.addWidget(self.leLocation)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.pbFileLocation = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pbFileLocation.setFont(font)
        self.pbFileLocation.setObjectName("pbFileLocation")
        self.verticalLayout_5.addWidget(self.pbFileLocation, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.pbGenerateVrtLayer = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pbGenerateVrtLayer.setFont(font)
        self.pbGenerateVrtLayer.setObjectName("pbGenerateVrtLayer")
        self.verticalLayout_3.addWidget(self.pbGenerateVrtLayer, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.fEVEL_settings)
        self.fButtons = QtWidgets.QFrame(self.fMainTools)
        self.fButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fButtons.setObjectName("fButtons")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.fButtons)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(411, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.pbCancel = QtWidgets.QPushButton(self.fButtons)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pbCancel.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\EVEL\\widgets\\../../icons/Icons_hele/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbCancel.setIcon(icon)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_7.addWidget(self.pbCancel)
        self.pbSave = QtWidgets.QPushButton(self.fButtons)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.pbSave.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\EVEL\\widgets\\../../icons/Icons_hele/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSave.setIcon(icon1)
        self.pbSave.setIconSize(QtCore.QSize(16, 16))
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_7.addWidget(self.pbSave)
        self.verticalLayout.addWidget(self.fButtons)
        self.horizontalLayout.addWidget(self.fMainTools)
        self.fHelpMenu = QtWidgets.QFrame(self.fMain)
        self.fHelpMenu.setMinimumSize(QtCore.QSize(200, 0))
        self.fHelpMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fHelpMenu.setStyleSheet("")
        self.fHelpMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fHelpMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fHelpMenu.setObjectName("fHelpMenu")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.fHelpMenu)
        self.verticalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.fHelpMenu)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.fHelpMenu)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_10.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.fHelpMenu)
        self.horizontalLayout_3.addWidget(self.fMain)

        self.retranslateUi(EVEL)
        QtCore.QMetaObject.connectSlotsByName(EVEL)

    def retranslateUi(self, EVEL):
        _translate = QtCore.QCoreApplication.translate
        EVEL.setWindowTitle(_translate("EVEL", "EVEL generaator"))
        self.groupBox_4.setTitle(_translate("EVEL", "Kiliendiga seotud"))
        self.cbFlowMeter.setText(_translate("EVEL", "Arvestid"))
        self.cbCustomer.setText(_translate("EVEL", "Kliendid"))
        self.cbDemarcationPoint.setText(_translate("EVEL", "Piritluspunktid"))
        self.cbApartment.setText(_translate("EVEL", "Korterid"))
        self.cbConnectionPoints.setText(_translate("EVEL", "Liitumispunktid"))
        self.cbEasements.setText(_translate("EVEL", "Servituudid"))
        self.cbContract.setText(_translate("EVEL", "Lepingud"))
        self.cbProperties.setText(_translate("EVEL", "Kinnistud"))
        self.groupBox_5.setTitle(_translate("EVEL", "Vesi"))
        self.cbWater.setText(_translate("EVEL", "Vesi"))
        self.cbFirePlug.setText(_translate("EVEL", "Tuletrjehüdrandid"))
        self.groupBox_6.setTitle(_translate("EVEL", "Isevoolne"))
        self.cbRainwater.setText(_translate("EVEL", "Sademevesi"))
        self.cbSewage.setText(_translate("EVEL", "Kanal"))
        self.groupBox_7.setTitle(_translate("EVEL", "Üldised seaded"))
        self.cbSNConstant.setText(_translate("EVEL", "SN-väärtused"))
        self.cbProgram.setText(_translate("EVEL", "Programmid"))
        self.groupBox_8.setTitle(_translate("EVEL", "Jaamad/seadmed"))
        self.cbPumpstation.setText(_translate("EVEL", "Pumpla"))
        self.cbSewTreatment.setText(_translate("EVEL", "Reoveepuhasti"))
        self.cbPressureStation.setText(_translate("EVEL", "Survejaamad"))
        self.cbDevice.setText(_translate("EVEL", "Seadmed"))
        self.groupBox.setTitle(_translate("EVEL", "EVEL andmekiht"))
        self.cbServices.setText(_translate("EVEL", "Võrgusündmused"))
        self.cbExternalDoc.setText(_translate("EVEL", "Välisdokumendid"))
        self.cbManhole.setText(_translate("EVEL", "Kaevud"))
        self.cbValve.setText(_translate("EVEL", "Ventiilid"))
        self.cbOperation.setText(_translate("EVEL", "Operatsioonid"))
        self.cbError.setText(_translate("EVEL", "Veateated"))
        self.groupBox_2.setTitle(_translate("EVEL", "Andmebaasi tüüp"))
        self.cbGepackage.setText(_translate("EVEL", "Geopakage"))
        self.cbSQLDatabase.setText(_translate("EVEL", "SQL"))
        self.cbPostgreDatabase.setText(_translate("EVEL", "Postgre"))
        self.groupBox_3.setTitle(_translate("EVEL", "Andmebaasi nimetus/asukoht"))
        self.label_2.setText(_translate("EVEL", "Nimetus"))
        self.label.setText(_translate("EVEL", "Asukoht"))
        self.pbFileLocation.setText(_translate("EVEL", "Määra faili asukoht"))
        self.pbGenerateVrtLayer.setText(_translate("EVEL", "Genereeri virtuaalkihid"))
        self.pbCancel.setText(_translate("EVEL", "Tühista"))
        self.pbSave.setText(_translate("EVEL", "Salvesta"))
        self.label_4.setText(_translate("EVEL", "Kuidas tööriista\n"
"kasutada?"))
        self.textEdit.setHtml(_translate("EVEL", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
