class Katastriyksus:
    fid = "fid"                # Baasis olev id
    tunnus = "tunnus"          # Katastriüksuse tunnus
    hkood = "hkood"            # Asustusüksuse kood
    mk_nimi = "mk_nimi"        # Maakonna nimetus
    ov_nimi = "ov_nimi"        # Omavalitsuse nimetus
    ay_nimi = "ay_nimi"        # Asustusüksuse nimetus
    l_aadress = "l_aadress"    # Lahiaadress
    registr = "registr"        # Katastriüksuse esmaregistreerimise kuupäev
    muudet = "muudet"          # Katastriüksuse viimase muudatuse kuupäev
    siht1 = "siht1"            # 1. sihtostarve
    siht2 = "siht2"            # 2. sihtostarve
    siht3 = "siht3"            # 3. sihtostarve
    so_prts1 = "so_prts1"      # 1. sihtostarbe protsent
    so_prts2 = "so_prts2"      # 2. sihtostarbe protsent
    so_prts3 = "so_prts3"      # 3. sihtostarbe protsent
    pindala = "pindala"        # Katastriüksuse pindala
    haritav = "haritav"        # Haritava maa kõlvik
    rohumaa = "rohumaa"        # Loodusliku rohumaa kõlvik
    mets = "mets"              # Metsamaa kõlvik
    ouemaa = "ouemaa"          # Õuemaa kõlvik
    muumaa = "muumaa"          # Muu maa kõlvik
    kinnistu = "kinnistu"      # Kinnistu registriosa number
    muutpohjus = "muutpohjus"  # Katatastriüksuse viimane muudatus
    omvorm = "omvorm"          # Katastriüksuse omandivorm
    maks_hind = "maks_hind"    # Maatüki maksustamishind
    marked = "marked"          # Katastriüksuse märked
    ads_oid = "ads_oid"        # ADS objekti identifikaator, identifitseerib objekti läbi versioonide.
    adob_id = "adob_id"        # Aadressiobjekti versiooni unikaalne identifikaator (unikaalne üle kõikide objektide kõikide versioonide).
    oiguslik_alus = "oiguslik_alus"  # Katastriüksuse viimase muudatuse õiguslik alus
    eksport = "eksport"        # Andmete väljavõtte kuupäev

class OldKatastriyksus:
    Tunnus = "TUNNUS"                            # Katastriüksuse tunnus
    Haldusyksuse_kood = "HKOOD"                  # Haldusüksuse kood
    Maakonna_nimi = "MK_NIMI"                    # Maakonna nimetus
    Omavalitsuse_nimi = "OV_NIMI"                # Omavalitsuse nimetus
    Asustusyksuse_nimi = "AY_NIMI"               # Asustusüksuse nimetus
    Lahiaadress = "L_AADRESS"                    # Lahiaadress
    Registreeritud = "REGISTR"                   # Katastriüksuse esmaregistreerimise kuupäev
    Muudetud = "MUUDET"                          # Katastriüksuse viimase muudatuse kuupäev
    Sihtotstarve_1 = "SIHT1"                     # 1. sihtostarve
    Sihtotstarve_2 = "SIHT2"                     # 2. sihtostarve
    Sihtotstarve_3 = "SIHT3"                     # 3. sihtostarve
    SO_protsent_1 = "SO_PRTS1"                   # 1. sihtostarbe protsent
    SO_protsent_2 = "SO_PRTS2"                   # 2. sihtostarbe protsent
    SO_protsent_3 = "SO_PRTS3"                   # 3. sihtostarbe protsent
    Pindala = "PINDALA"                          # Katastriüksuse pindala
    Ruumikuju_pindala = "RUUMPIND"               # Katastriüksuse ruumikuju pindala
    Registreeritud_yhik = "REG_YHIK"             # Pindala registreerimise ühik
    Haritav_maa = "HARITAV"                      # Haritava maa kõlvik
    Looduslik_rohumaa = "ROHUMAA"                # Loodusliku rohumaa kõlvik
    Metsamaa = "METS"                            # Metsamaa kõlvik
    Ouemaa = "OUEMAA"                            # Õuemaa kõlvik
    Muu_maa = "MUUMAA"                           # Muu maa kõlvik
    Kinnistu_nr = "KINNISTU"                     # Kinnistu registriosa number
    Moodustatud = "MOODUST"                      # Maamõõtmise kuupäev
    Moodistaja = "MOOTJA"                        # Maamõõtja nimetus
    Moodustamisviis = "MOOTVIIS"                 # Moodustamisviis
    Registreerimisviis = "OMVIIS"                # Katastriüksuse registreerimise viis
    Omandivorm = "OMVORM"                        # Katastriüksuse omandivorm
    Maksustamishind = "MAKS_HIND"                # Maa-ameti arvutatud maaüksuse maksustamishind €
    Marketekst = "MARKETEKST"                    # Katastriüksuse märked

