class SnValues:
 values = {
    (0, 'BUILDING_AREA_LOCATION', 'Maa-alune', None, 'Rajatise paiknemine', None),
    (1, 'BUILDING_AREA_LOCATION', 'Maapealne', None, None, None),
    (2, 'BUILDING_AREA_TYPE', 'Reovee eelpuhastid', None, 'Rajatise tüüp', None),
    (3, 'BUILDING_AREA_TYPE', 'Reoveepuhastid', None, None, None),
    (4, 'BUILDING_AREA_TYPE', 'Settetöötlus', None, None, None),
    (5, 'BUILDING_AREA_TYPE', 'Bioloogiline puhastus', None, None, None),
    (6, 'BUILDING_AREA_TYPE', 'Mehhaaniline puhastus', None, None, None),
    (7, 'BUILDING_AREA_TYPE', 'Muud rajatised', None, None, None),
    (8, 'BUILDING_AREA_TYPE_SUB', 'Rasvapüüdur', None, 'Rajatise alamtüüp', None),
    (9, 'BUILDING_AREA_TYPE_SUB', 'Õlipüüdur', None, None, None),
    (10, 'BUILDING_AREA_TYPE_SUB', 'Liivapüüdur', None, None, None),
    (11, 'BUILDING_AREA_TYPE_SUB', 'Sademevee imbväljak', None, None, None),
    (12, 'BUILDING_AREA_TYPE_SUB', 'Sademevee mahuti', None, None, None),
    (13, 'BUILDING_AREA_TYPE_SUB', 'Kaevurake', None, None, None),
    (14, 'BUILDING_AREA_TYPE_SUB', 'Hülss', None, None, None),
    (15, 'CONDITION_CLASS', '0', None, 'Seisukorra info', None),
    (16, 'CONDITION_CLASS', '1', None, None, None),
    (17, 'CONDITION_CLASS', '2', None, None, None),
    (18, 'CONDITION_CLASS', '3', None, None, None),
    (19, 'CONDITION_CLASS', '4', None, None, None),
    (20, 'CONSUMERPOINT_GROUP', 'Normaalarveldatavad', None, 'Tarbimispunkti grupp', None),
    (21, 'CONSUMERPOINT_GROUP', 'Suvevesi', None, None, None),
    (22, 'CONSUMERPOINT_GROUP', 'Pea-ja kõrvalmõõtjaga', None, None, None),
    (23, 'CONSUMERPOINT_STATE', 'Määramata', None, 'Tarbimispunkti olek', None),
    (24, 'CONSUMERPOINT_STATE', 'Aktiivne', None, None, None),
    (25, 'CONSUMERPOINT_STATE', 'Leping sõlmimisel', None, None, None),
    (26, 'CONSUMERPOINT_STATE', 'Kandidaat', None, None, None),
    (27, 'CONSUMERPOINT_TYPE', 'Määramata', None, 'Tarbimispunkti tüüp', None),
    (28, 'CONSUMERPOINT_TYPE', 'Ühepereelamu', None, None, None),
    (29, 'CONSUMERPOINT_TYPE', 'Kortermaja', None, None, None),
    (30, 'CONSUMERPOINT_TYPE', 'Tööstus', None, None, None),
    (31, 'CONSUMERPOINT_TYPE', 'Püstikkraan', None, None, None),
    (32, 'CONTRACT_TYPE', 'Liitumisleping', None, 'Lepingu tüüp', None),
    (33, 'CONTRACT_TYPE', 'Tarbimisleping', None, None, None),
    (34, 'CUSTOMER_ROLE', 'Määramata', None, 'Tarbija roll', None),
    (35, 'CUSTOMER_ROLE', 'Omanik', None, None, None),
    (36, 'CUSTOMER_ROLE', 'Rentnik', None, None, None),
    (37, 'CUSTOMER_STATE', 'Aktiivne', None, 'Tarbija olek', None),
    (38, 'CUSTOMER_STATE', 'Mitteaktiivne', None, None, None),
    (39, 'CUSTOMER_TYPE', 'Määramata', None, 'Tarbija tüüp', None),
    (40, 'CUSTOMER_TYPE', 'Era', None, None, None),
    (41, 'CUSTOMER_TYPE', 'Äri', None, None, None),
    (42, 'CUSTOMER_TYPE', 'Munitsipaal', None, None, None),
    (43, 'DEVICE_TYPE', 'Määramata', None, 'Seadme tüüp', None),
    (44, 'DEVICE_TYPE', 'Kompressor', None, None, None),
    (45, 'DEVICE_TYPE', 'Segur', None, None, None),
    (46, 'DH_DUCT_DIAMETER', '32', None, 'Kaugküttetoru diameeter', None),
    (47, 'DH_DUCT_DIAMETER', '50', None, None, None),
    (48, 'DH_DUCT_DIAMETER', '65', None, None, None),
    (49, 'DH_DUCT_DIAMETER', '80', None, None, None),
    (50, 'DH_DUCT_DIAMETER', '90', None, None, None),
    (51, 'DH_DUCT_DIAMETER', '100', None, None, None),
    (52, 'DH_DUCT_DIAMETER', '110', None, None, None),
    (53, 'DH_DUCT_DIAMETER', '125', None, None, None),
    (54, 'DH_DUCT_DIAMETER', '150', None, None, None),
    (55, 'DH_DUCT_DIAMETER', '200', None, None, None),
    (56, 'DH_DUCT_DIAMETER', '250', None, None, None),
    (57, 'DH_DUCT_DIAMETER', '800', None, None, None),
    (58, 'DH_DUCT_DIAMETER', '1200', None, None, None),
    (59, 'DH_DUCT_MATERIAL', 'Määramata', None, 'Kaugküttetoru materjal', None),
    (60, 'DH_DUCT_MATERIAL', 'Teras', None, None, None),
    (61, 'DH_DUCT_MATERIAL', 'Plast', None, None, None),
    (62, 'DH_DUCT_ROLE', 'Määramata', None, 'Kaugküttetoru roll', None),
    (63, 'DH_DUCT_ROLE', 'Pealevool', None, None, None),
    (64, 'DH_DUCT_ROLE', 'Tagasivool', None, None, None),
    (65, 'DH_DUCT_SHELL_DIAMETER', 'Määramata', None, 'Kaugküttetoru isolatsiooni läbimõõt', None),
    (66, 'DH_DUCT_SHELL_DIAMETER', '125', None, None, None),
    (67, 'DH_DUCT_SHELL_DIAMETER', '140', None, None, None),
    (68, 'DH_DUCT_SHELL_DIAMETER', '160', None, None, None),
    (69, 'DH_DUCT_SHELL_DIAMETER', '180', None, None, None),
    (70, 'DH_DUCT_SHELL_DIAMETER', '225', None, None, None),
    (71, 'DH_DUCT_SHELL_DIAMETER', '250', None, None, None),
    (72, 'DH_DUCT_SHELL_DIAMETER', '355', None, None, None),
    (73, 'DH_DUCT_SHELL_TYPE', 'Isoleerimata', None, 'Kaugküttetoru isolatsiooni tüüp', None),
    (74, 'DH_DUCT_SHELL_TYPE', 'Eelisoleeritud', None, None, None),
    (75, 'DH_DUCT_SHELL_TYPE', 'Paaris eelisoleeritud', None, None, None),
    (76, 'DH_DUCT_SHELL', 'Määramata', None, 'Küttetoru kesta materjal', None),
    (77, 'DH_DUCT_SHELL', 'Ruberoid', None, None, None),
    (78, 'DH_DUCT_SHELL', 'Plast', None, None, None),
    (79, 'DH_DUCT_SHELL_MATERIAL', 'Määramata', None, 'Küttetoru soojustuse materjal', None),
    (80, 'DH_DUCT_SHELL_MATERIAL', 'Vill', None, None, None),
    (81, 'DH_DUCT_SHELL_MATERIAL', 'Vaht', None, None, None),
    (82, 'DH_MANHOLE_DIAMETER', 'Määramata', None, 'Soojakaevu mõõtmed', None),
    (83, 'DH_MANHOLE_DIAMETER', '3000x3000 ', None, None, None),
    (84, 'DH_MANHOLE_DIAMETER', '700', None, None, None),
    (85, 'DH_MANHOLE_TYPE', 'Määramata', None, 'Soojakaevu tüüp', None),
    (86, 'DH_MANHOLE_TYPE', 'Kamber', None, None, None),
    (87, 'DH_METER_TYPE', 'Määramata', None, 'Soojaarvesti tüüp', None),
    (88, 'DH_METER_TYPE', 'Mehaaniline', None, None, None),
    (89, 'DH_METER_TYPE', 'Ultraheli', None, None, None),
    (90, 'DH_NODE_GROUP', 'Liitmikud', None, 'Küttesõlme grupp', None),
    (91, 'DH_NODE_GROUP', 'Sulgeseadmed', None, None, None),
    (92, 'DH_NODE_GROUP', 'Seadmed', None, None, None),
    (93, 'DH_NODE_GROUP', 'Rajatised', None, None, None),
    (94, 'DH_NODE_GROUP', 'Muu', None, None, None),
    (95, 'DH_NODE_TYPE', 'Hargmik', 'Liitmikud', 'Küttesõlme alamgrupp', None),
    (96, 'DH_NODE_TYPE', 'Pimeots', 'Liitmikud', None, None),
    (97, 'DH_NODE_TYPE', 'Läbimõõdu üleminek', 'Liitmikud', None, None),
    (98, 'DH_NODE_TYPE', 'Maakraan', 'Sulgeseade', None, None),
    (99, 'DH_NODE_TYPE', 'Peasiiber', 'Sulgeseade', None, None),
    (100, 'DH_NODE_TYPE', 'Majaühenduse siiber', 'Sulgeseade', None, None),
    (101, 'DH_NODE_TYPE', 'Teenindussõlm', 'Rajatis', None, None),
    (102, 'DH_NODE_TYPE', 'Kaugküttekilp', 'Rajatis', None, None),
    (103, 'DH_NODE_TYPE', 'Mõõtekarp', 'Muu', None, None),
    (104, 'DIAMETER_TYPE', 'De', None, 'Läbimõõdu tüüp', None),
    (105, 'DIAMETER_TYPE', 'Di', None, None, None),
    (106, 'DIAMETER_TYPE', 'Dn', None, None, None),
    (107, 'DUCT_TYPE', 'Tüvitoru', None, 'Otstarve', None),
    (108, 'DUCT_TYPE', 'Peatoru', None, None, None),
    (109, 'DUCT_TYPE', 'Ühendustoru', None, None, None),
    (110, 'DUCT_TYPE', 'Tarbijatoru', None, None, None),
    (111, 'DUCT_TYPE', 'Kraav', None, None, None),
    (112, 'DUCT_TYPE', 'Renn', None, None, None),
    (113, 'EL_CABLE_MARK', 'Määramata', None, 'Elektrikaabli mark', None),
    (114, 'EL_CABLE_MARK', 'AXPK-4G25', None, None, None),
    (115, 'EL_CABLE_MARK', 'AXPK-4G35', None, None, None),
    (116, 'EL_MAIN_FUSE_TYPE', 'Määramata', None, 'Peakaitsme suurus', None),
    (117, 'EL_MAIN_FUSE_TYPE', '10', None, None, None),
    (118, 'EL_MAIN_FUSE_TYPE', '20', None, None, None),
    (119, 'EL_METER_TYPE', 'Määramata', None, 'Elektriarvesti tüüp', None),
    (120, 'EL_METER_TYPE', 'Mehaaniline', None, None, None),
    (121, 'EL_METER_TYPE', 'Digitaalne', None, None, None),
    (122, 'EL_NODE_GROUP', 'Alajaam', None, 'Elektrisõlme grupp', None),
    (123, 'EL_NODE_GROUP', 'Kilp', None, None, None),
    (124, 'EL_NODE_GROUP', 'Muhv', None, None, None),
    (125, 'EL_NODE_GROUP', 'Valguskoht', None, None, None),
    (126, 'EL_NODE_TYPE', 'Mastalajaam', 'Alajaam', 'Elektrisõlme alamgrupp', None),
    (127, 'EL_NODE_TYPE', 'Alajaam', 'Alajaam', None, None),
    (128, 'EL_NODE_TYPE', 'Jaotuskilp', 'Kilp', None, None),
    (129, 'EL_NODE_TYPE', 'Liitumiskilp', 'Kilp', None, None),
    (130, 'EL_NODE_TYPE', 'Post', 'Valguskoht', None, None),
    (131, 'EL_NODE_TYPE', 'Sein', 'Valguskoht', None, None),
    (132, 'EL_NODE_TYPE', 'Riputus', 'Valguskoht', None, None),
    (133, 'EL_NODE_TYPE', 'Maa', 'Valguskoht', None, None),
    (134, 'EXT_DOC_CATEGORY', 'Üldine', None, 'Dokumentide kategooria', None),
    (135, 'EXT_DOC_CATEGORY', 'Leping', None, None, None),
    (136, 'EXT_DOC_TYPE', 'Teostusjoonis', None, 'Dokumentide tüüp', None),
    (137, 'EXT_DOC_TYPE', 'Foto', None, None, None),
    (138, 'EXT_DOC_TYPE', 'DigiDoc', None, None, None),
    (139, 'FAILURE_CAUSE', 'Määramata', None, 'Rikke põhjus', None),
    (140, 'FAILURE_CAUSE', 'Külmumine', None, None, None),
    (141, 'FAILURE_CAUSE', 'Lõhkumine', None, None, None),
    (142, 'FAILURE_CAUSE', 'Ummistus', None, None, None),
    (143, 'FAILURE_NOT_VALID', 'Kuulub lahendamisele', None, 'Vea kuuluvus', None),
    (144, 'FAILURE_NOT_VALID', 'Ei kuulu lahendamisele', None, None, None),
    (145, 'FAILURE_SEVERITY', 'Määramata', None, 'Raskusaste', None),
    (146, 'FAILURE_SEVERITY', 'Kerge', None, None, None),
    (147, 'FAILURE_SEVERITY', 'Keskmine', None, None, None),
    (148, 'FAILURE_SEVERITY', 'Vajab kohest sekkumist', None, None, None),
    (149, 'FAILURE_SEVERITY', 'Raske', None, None, None),
    (150, 'FAILURE_TYPE', 'Määramata', None, 'Vea tüüp', None),
    (151, 'FAILURE_TYPE', 'Leke', None, None, None),
    (152, 'FAILURE_TYPE', 'Madal surve', None, None, None),
    (153, 'FAILURE_TYPE', 'Ummistus', None, None, None),
    (154, 'FIRE_PLUG_LOCATION', 'Määramata', None, 'Hüdrandi paiknemine', None),
    (155, 'FIRE_PLUG_LOCATION', 'Maapealne', None, None, None),
    (156, 'FIRE_PLUG_LOCATION', 'Hoonel', None, None, None),
    (157, 'FIRE_PLUG_LOCATION', 'Kaevus', None, None, None),
    (158, 'FIRE_PLUG_TYPE', 'Määramata', None, 'Hüdrandi tüüp', None),
    (159, 'FIRE_PLUG_TYPE', 'Tuletõrjehüdrant', None, None, None),
    (160, 'FIRE_PLUG_TYPE_SUB', 'Määramata', None, 'Hüdrandi alamtüüp', None),
    (161, 'FIRE_PLUG_TYPE_SUB', 'T', None, None, None),
    (162, 'FIRE_PLUG_TYPE_SUB', 'TS', None, None, None),
    (163, 'FIRMNESS_CLASS', 'Määramata', None, 'Ringjäikus', None),
    (164, 'FLOWMETER_CLASS', 'Määramata', None, 'Veemõõtja klass', None),
    (165, 'FLOWMETER_CLASS', 'Peaarvesti', None, None, None),
    (166, 'FLOWMETER_CLASS', 'Kõrvalarvesti', None, None, None),
    (167, 'FLOWMETER_CONSOLE', 'Määramata', None, 'Veearvesti konsooli pikkus', None),
    (168, 'FLOWMETER_CONSOLE', '175', None, None, None),
    (169, 'FLOWMETER_SIZE', 'Määramata', None, 'Veearvesti toru läbimõõt', None),
    (170, 'FLOWMETER_SIZE', 'DN10', None, None, None),
    (171, 'FLOWMETER_SIZE', 'DN15', None, None, None),
    (172, 'FLOWMETER_SIZE', 'DN20', None, None, None),
    (173, 'FLOWMETER_SIZE', 'DN25', None, None, None),
    (174, 'FLOWMETER_SIZE', 'DN32', None, None, None),
    (175, 'FLOWMETER_SIZE', 'DN40', None, None, None),
    (176, 'FLOWMETER_SIZE', 'DN50', None, None, None),
    (177, 'FLOWMETER_SIZE', 'DN63', None, None, None),
    (178, 'FLOWMETER_SIZE', 'DN100', None, None, None),
    (179, 'FLOWMETER_SIZE', 'DN160', None, None, None),
    (180, 'FLOWMETER_SIZE', 'DN200', None, None, None),
    (181, 'FLOWMETER_TYPE', 'Määramata', None, 'Veemõõtja tüüp', None),
    (182, 'FLOWMETER_TYPE', 'Mehaaniline', None, None, None),
    (183, 'FLOWMETER_TYPE', 'Ultraheli', None, None, None),
    (184, 'FLOWMETER_WATER_TYPE', 'Määramata', None, 'Mõõdetava vee liik', None),
    (185, 'FLOWMETER_WATER_TYPE', 'Joogivesi', None, None, None),
    (186, 'FLOWMETER_WATER_TYPE', 'Kastmisvesi', None, None, None),
    (187, 'FLOWMETER_WATER_TYPE', 'Toorvesi', None, None, None),
    (188, 'FLOWMETER_WATER_TYPE', 'Reovesi', None, None, None),
    (189, 'FORM_CODE', 'Määramata', None, 'Toru kuju', None),
    (190, 'FORM_CODE', 'Ümmargune', None, None, None),
    (191, 'FORM_CODE', 'Neljakandiline', None, None, None),
    (192, 'FREE_AREA_TYPE', 'Tegevuspiirkond', None, 'Piirkondade tüüp', None),
    (193, 'FREE_AREA_TYPE', 'Veehaardeala', None, None, None),
    (194, 'FREE_AREA_TYPE', 'Reoveekogumisala', None, None, None),
    (195, 'FREE_AREA_TYPE', 'Sanitaarkaitseala', None, None, None),
    (196, 'FREE_AREA_TYPE', 'Kuja', None, None, None),
    (197, 'FREE_AREA_TYPE', 'Niitmisala', None, None, None),
    (198, 'FREE_AREA_TYPE', 'Lumekoristusala', None, None, None),
    (199, 'FREE_LINE_TYPE', 'Märkejoon', None, 'Vaba joone tüüp', None),
    (200, 'FREE_LINE_TYPE', 'Maanduskontuur', None, None, None),
    (201, 'GAS_DUCT_DIAMETER', '20', None, 'Gaasitoru diameeter', None),
    (202, 'GAS_DUCT_DIAMETER', '25', None, None, None),
    (203, 'GAS_DUCT_DIAMETER', '32', None, None, None),
    (204, 'GAS_DUCT_DIAMETER', '40', None, None, None),
    (205, 'GAS_DUCT_DIAMETER', '50', None, None, None),
    (206, 'GAS_DUCT_DIAMETER', '63', None, None, None),
    (207, 'GAS_DUCT_DIAMETER', '75', None, None, None),
    (208, 'GAS_DUCT_DIAMETER', '90', None, None, None),
    (209, 'GAS_DUCT_DIAMETER', '100', None, None, None),
    (210, 'GAS_DUCT_DIAMETER', '110', None, None, None),
    (211, 'GAS_DUCT_DIAMETER', '125', None, None, None),
    (212, 'GAS_DUCT_DIAMETER', '140', None, None, None),
    (213, 'GAS_DUCT_DIAMETER', '160', None, None, None),
    (214, 'GAS_DUCT_DIAMETER', '180', None, None, None),
    (215, 'GAS_DUCT_DIAMETER', '200', None, None, None),
    (216, 'GAS_DUCT_DIAMETER', '225', None, None, None),
    (217, 'GAS_DUCT_MATERIAL', 'Määramata', None, 'Gaasitoru materjal', None),
    (218, 'GAS_DUCT_MATERIAL', 'Teras', None, None, None),
    (219, 'GAS_DUCT_MATERIAL', 'Plast', None, None, None),
    (220, 'GAS_MANHOLE_DIAMETER', 'Määramata', None, 'Gaasikaevu mõõtmed', None),
    (221, 'GAS_MANHOLE_DIAMETER', '3000x3000 ', None, None, None),
    (222, 'GAS_MANHOLE_DIAMETER', '1000', None, None, None),
    (223, 'GAS_MANHOLE_DIAMETER', '1500', None, None, None),
    (224, 'GAS_MANHOLE_DIAMETER', '2000', None, None, None),
    (225, 'GAS_MANHOLE_TYPE', 'Gaasikaev', None, 'Gaasikaevu tüüp', None),
    (226, 'GAS_METER_TYPE', 'Määramata', None, 'Gaasiarvesti tüüp', None),
    (227, 'GAS_METER_TYPE', 'Membraan', None, None, None),
    (228, 'GAS_METER_TYPE', 'Rootor', None, None, None),
    (229, 'GAS_METER_TYPE', 'Turbiin', None, None, None),
    (230, 'GAS_METER_TYPE', 'Ultraheli', None, None, None),
    (231, 'GAS_NODE_GROUP', 'Liitmikud', None, 'Gaasisõlme grupp', None),
    (232, 'GAS_NODE_GROUP', 'Sulgeseadmed', None, None, None),
    (233, 'GAS_NODE_GROUP', 'Seadmed', None, None, None),
    (234, 'GAS_NODE_GROUP', 'Rajatised', None, None, None),
    (235, 'GAS_NODE_TYPE', 'Muhv', 'Liitmikud', 'Gaasisõlme alamgrupp', None),
    (236, 'GAS_NODE_TYPE', 'Pimeots', 'Liitmikud', None, None),
    (237, 'GAS_NODE_TYPE', 'Läbimõõdu üleminek', 'Liitmikud', None, None),
    (238, 'GAS_NODE_TYPE', 'Maakraan', 'Sulgeseade', None, None),
    (239, 'GAS_NODE_TYPE', 'Peasiiber', 'Sulgeseade', None, None),
    (240, 'GAS_NODE_TYPE', 'Majaühenduse siiber', 'Sulgeseade', None, None),
    (241, 'GAS_NODE_TYPE', 'Gaasijaotusjaam', 'Rajatis', None, None),
    (242, 'GAS_NODE_TYPE', 'Gaasikapp', 'Rajatis', None, None),
    (243, 'GAS_NODE_TYPE', 'Hüdrolukk', 'Seade', None, None),
    (244, 'GAS_NODE_TYPE', 'W-kondensaadikogur', 'Seade', None, None),
    (245, 'GAS_NODE_TYPE', 'Andmeedastusseade', 'Seade', None, None),
    (246, 'GAS_NODE_TYPE', 'Katoodkaitsemuundur', 'Seade', None, None),
    (247, 'GAS_PRESSURE_CLASS', 'Määramata', None, 'Gaasi surveklass', None),
    (248, 'GAS_PRESSURE_CLASS', 'A', None, None, None),
    (249, 'GAS_PRESSURE_CLASS', 'B', None, None, None),
    (250, 'GAS_PRESSURE_CLASS', 'C', None, None, None),
    (251, 'GAS_PRESSURE_CLASS', 'D', None, None, None),
    (252, 'HEIGHT_ACCURACY', 'Määramata', None, 'Kõrguse täpsus', None),
    (253, 'HEIGHT_ACCURACY', '2 cm', None, None, None),
    (254, 'HEIGHT_ACCURACY', '5 cm', None, None, None),
    (255, 'HEIGHT_ACCURACY', '10 cm', None, None, None),
    (256, 'HEIGHT_ACCURACY', '50 cm', None, None, None),
    (257, 'HEIGHT_ACCURACY', '1 m', None, None, None),
    (258, 'HEIGHT_ACCURACY', '5 m', None, None, None),
    (259, 'LAND_PERM_STATE', 'Tegemisel', None, 'Servituudi olek', None),
    (260, 'LAND_PERM_STATE', 'Sõlmitud', None, None, None),
    (261, 'LAND_PERM_TYPE', 'Lihtkirjalik', None, 'Servituudi liik', None),
    (262, 'LAND_PERM_TYPE', 'Notariaalne', None, None, None),
    (263, 'LAND_PERM_TYPE', 'Seadusest tulenev', None, None, None),
    (264, 'LAND_PERM_TYPE', 'Sundvaldus', None, None, None),
    (265, 'LID_CAPACITY', 'Määramata', None, 'Kaane kandevõime', None),
    (266, 'LID_CAPACITY', '25', None, None, None),
    (267, 'LID_CAPACITY', '40', None, None, None),
    (268, 'LID_DIAMETER', '200', None, 'Kaane mõõtmed', None),
    (269, 'LID_DIAMETER', '400', None, None, None),
    (270, 'LID_DIAMETER', '500', None, None, None),
    (271, 'LID_DIAMETER', '600', None, None, None),
    (272, 'LID_DIAMETER', '640', None, None, None),
    (273, 'LID_DIAMETER', '700', None, None, None),
    (274, 'LID_DIAMETER', '800', None, None, None),
    (275, 'LID_MATERIAL', 'Määramata', None, 'Kaane materjal', None),
    (276, 'LID_MATERIAL', 'Betoon', None, None, None),
    (277, 'LID_MATERIAL', 'Malm', None, None, None),
    (278, 'LID_MATERIAL', 'Plast', None, None, None),
    (279, 'LID_MATERIAL', 'Puit', None, None, None),
    (280, 'LID_MATERIAL', 'Teras', None, None, None),
    (281, 'LID_SHAPE', 'Määramata', None, 'Kaane kuju', None),
    (282, 'LID_SHAPE', 'Ümar', None, None, None),
    (283, 'LID_SHAPE', 'Nelinurkne', None, None, None),
    (284, 'LID_TYPE', 'Määramata', None, 'Kaane tüüp', None),
    (285, 'LID_TYPE', 'Rest', None, None, None),
    (286, 'LID_TYPE', 'Kinnine', None, None, None),
    (287, 'LIGHT_MARK', 'Teadmata', None, 'Valgusti mark', None),
    (288, 'LIGHT_TYPE', 'Määramata', None, 'Valgusti tüüp', None),
    (289, 'LIGHT_TYPE', 'Led', None, None, None),
    (290, 'LIGHT_TYPE', 'Halogeen', None, None, None),
    (291, 'LIGHT_TYPE', 'Naatrium', None, None, None),
    (292, 'LOCATION', 'Maapealne', None, 'Toru või kaabli paiknemine', None),
    (293, 'LOCATION', 'Maa-alune', None, None, None),
    (294, 'LOCATION', 'Veealune', None, None, None),
    (295, 'LOCATION', 'Hoones', None, None, None),
    (296, 'LOCATION', 'Õhus', None, None, None),
    (297, 'LOCATION', 'Torus', None, None, None),
    (298, 'LOCATION', 'Künas', None, None, None),
    (299, 'LOCATION_ACCURACY', 'Määramata', None, 'Asukoha täpsus', None),
    (300, 'LOCATION_ACCURACY', '2 cm', None, None, None),
    (301, 'LOCATION_ACCURACY', '10 cm', None, None, None),
    (302, 'LOCATION_ACCURACY', '50 cm', None, None, None),
    (303, 'LOCATION_ACCURACY', '1 m', None, None, None),
    (304, 'LOCATION_ACCURACY', '5 m', None, None, None),
    (305, 'MAPPING_METHOD', 'Määramata', None, 'Kaardistuse meetod', None),
    (306, 'MAPPING_METHOD', 'Teostusjoonis', None, None, None),
    (307, 'MAPPING_METHOD', 'Digitud', None, None, None),
    (308, 'NET_TYPE', 'Surve', None, 'Võrgu tüüp', None),
    (309, 'NET_TYPE', 'Isevoolne', None, None, None),
    (310, 'NET_TYPE', 'Vaakum', None, None, None),
    (311, None, None, None, None, None),
    (312, 'NETWORK', 'Vesi', None, 'Võrk', None),
    (313, 'NETWORK', 'Tuletõrjevesi', None, None, None),
    (314, 'NETWORK', 'Toorvesi', None, None, None),
    (315, 'NETWORK', 'Reovesi', None, None, None),
    (316, 'NETWORK', 'Sademevesi', None, None, None),
    (317, 'NETWORK', 'Drenaaž', None, None, None),
    (318, 'NETWORK', 'Ühisvoolne', None, None, None),
    (319, 'NETWORK', 'Tänavavalgustus', None, 'Teenindatav võrk', None),
    (320, 'NETWORK', 'Elekter', None, None, None),
    (321, 'OPEN_STATE', 'Määramata', None, 'Sõlme olek', None),
    (322, 'OPEN_STATE', 'Avatud', None, None, None),
    (323, 'OPEN_STATE', 'Suletud', None, None, None),
    (324, 'OPERATION', 'Määramata', None, 'Avarii/remonttöö liik', None),
    (325, 'OPERATION', 'Läbipesu', None, None, None),
    (326, 'OPERATION', 'Remondimuhvi paigaldus', None, None, None),
    (327, 'OPERATION', 'Läbikeeramine', None, None, None),
    (328, 'OPERATION', 'Puhastamine', None, None, None),
    (329, 'OWNER', 'Määramata', None, 'Omanik', None),
    (330, 'OWNER', 'Veevärk', None, None, None),
    (331, 'OWNER', 'Klient', None, None, None),
    (332, 'OWNER', 'Arendaja', None, None, None),
    (333, 'OWNER', 'Teine veevärk', None, None, None),
    (334, 'OWNER', 'KOV', None, None, None),
    (335, 'LESSEE', 'Määramata', None, 'Rentnik', None),
    (336, 'LESSEE', 'Veevärk', None, None, None),
    (337, 'LESSEE', 'Teine veevärk', None, None, None),
    (338, 'PLAN_STATE', 'Projekteerimisel', None, 'Graafiliste andmete olek', None),
    (339, 'PLAN_STATE', 'Töös', None, None, None),
    (340, 'PLAN_STATE', 'Valmis', None, None, None),
    (341, 'PLAN_STATE', 'Kasutusest eemaldatud', None, None, None),
    (342, 'PLAN_TYPE', 'Määramata', None, 'Graafiliste andmete tüüp', None),
    (343, 'PLAN_TYPE', 'Projekt', None, None, None),
    (344, 'PLAN_TYPE', 'Geoalus', None, None, None),
    (345, 'PLAN_TYPE', 'Teostusjoonis', None, None, None),
    (346, 'PLAN_TYPE', 'Muu', None, None, None),
    (347, 'POLE_MATERIAL', 'Määramata', None, 'Posti materjal', None),
    (348, 'POLE_MATERIAL', 'Puit', None, None, None),
    (349, 'POLE_MATERIAL', 'Betoon', None, None, None),
    (350, 'POLE_MATERIAL', 'Metall', None, None, None),
    (351, 'POLE_MATERIAL', 'Plastik', None, None, None),
    (352, 'POLE_STANCHION_TYPE', 'Määramata', None, 'Jalandi tüüp', None),
    (353, 'POLE_STANCHION_TYPE', 'Betoon', None, None, None),
    (354, 'POLE_STANCHION_TYPE', 'Puit', None, None, None),
    (355, 'POLE_STANCHION_TYPE', 'Teras', None, None, None),
    (356, 'POLE_STANCHION_TYPE', 'RBJ-4', None, None, None),
    (357, 'PRESSURE_CLASS', 'PN6', None, 'Rõhuklass', None),
    (358, 'PRESSURE_CLASS', 'PN10', None, None, None),
    (359, 'PRESSURE_CLASS', 'PN16', None, None, None),
    (360, 'PROGRAM_GROUP', 'Määramata', None, 'Hooldustööde grupp', None),
    (361, 'PROGRAM_GROUP', 'Hooldustööd', None, None, None),
    (362, 'PROGRAM_GROUP', 'Renoveerimistööd', None, None, None),
    (363, 'PS_MATERIAL', 'Määramata', None, 'Pumbajaama materjal', None),
    (364, 'PS_MATERIAL', 'Betoon', None, None, None),
    (365, 'PS_MATERIAL', 'Puit', None, None, None),
    (366, 'PS_MATERIAL', 'Tellis', None, None, None),
    (367, 'PS_MATERIAL', 'Plastik', None, None, None),
    (368, 'PS_MATERIAL', 'Klaaskiud', None, None, None),
    (369, 'PS_ROLE', 'Määramata', None, 'Pumbajaama roll', None),
    (370, 'PS_ROLE', 'Peapumpla', None, None, None),
    (371, 'PS_ROLE', 'Vahepumpla', None, None, None),
    (372, 'PS_ROLE', 'Rõhutõstepumpla', None, None, None),
    (373, 'PS_WATER_SOURCE', 'Määramata', None, 'Veeallikas', None),
    (374, 'PS_WATER_SOURCE', 'Veekogu', None, None, None),
    (375, 'PS_WATER_SOURCE', 'Põhjavesi', None, None, None),
    (376, 'PS_WATER_TYPE', 'Määramata', None, 'Vee tüüp', None),
    (377, 'PS_WATER_TYPE', 'Toorvesi', None, None, None),
    (378, 'PS_WATER_TYPE', 'Olmevesi', None, None, None),
    (379, 'PS_WATER_TYPE', 'Tehnovesi', None, None, None),
    (380, 'PS_WATER_TYPE', 'Tuletõrjevesi', None, None, None),
    (381, 'PUMP_INSTALL_METHOD', 'Määramata', None, 'Pumba paigaldusviis', None),
    (382, 'PUMP_INSTALL_METHOD', 'Kuiv', None, None, None),
    (383, 'PUMP_INSTALL_METHOD', 'Märg', None, None, None),
    (384, 'STATE_INFO', 'Avarii', None, 'Sõlme oleku info', None),
    (385, 'STATE_INFO', 'Maksmata arve', None, None, None),
    (386, 'SURVEY_STANDARD', 'Määramata', None, 'Mõõdistuse standard', None),
    (387, 'SURVEY_STANDARD', 'MKM/BK77', None, None, None),
    (388, 'SURVEY_STANDARD', 'MKM/EH2000', None, None, None),
    (389, 'SURVEY_STANDARD', 'MKM/EH2000/EVEL', None, None, None),
    (390, 'SURVEY_TYPE', 'Geoalus', None, 'Joonise tüüp', None),
    (391, 'SURVEY_TYPE', 'Teostusjoonis', None, None, None),
    (392, 'SW_BRANCH_TYPE', 'Määramata', None, 'Kanalisatsiooni liitmiku tüüp', None),
    (393, 'SW_BRANCH_TYPE', 'Remondimuhv', None, None, None),
    (394, 'SW_BRANCH_TYPE', 'Pimeots/Pimeäärik', None, None, None),
    (395, 'SW_BRANCH_TYPE', 'Ühenduskoht', None, None, None),
    (396, 'SW_BRANCH_TYPE_SUB', 'Määramata', None, 'Kanalisatsiooni liitmiku alamtüüp', None),
    (397, 'SW_DUCT_DIAMETER', '100', None, 'Kanali toru diameeter', None),
    (398, 'SW_DUCT_DIAMETER', '110', None, None, None),
    (399, 'SW_DUCT_DIAMETER', '125', None, None, None),
    (400, 'SW_DUCT_DIAMETER', '150', None, None, None),
    (401, 'SW_DUCT_DIAMETER', '160', None, None, None),
    (402, 'SW_DUCT_DIAMETER', '200', None, None, None),
    (403, 'SW_DUCT_DIAMETER', '225', None, None, None),
    (404, 'SW_DUCT_DIAMETER', '250', None, None, None),
    (405, 'SW_DUCT_DIAMETER', '280', None, None, None),
    (406, 'SW_DUCT_DIAMETER', '300', None, None, None),
    (407, 'SW_DUCT_DIAMETER', '315', None, None, None),
    (408, 'SW_DUCT_DIAMETER', '350', None, None, None),
    (409, 'SW_DUCT_DIAMETER', '400', None, None, None),
    (410, 'SW_DUCT_DIAMETER', '450', None, None, None),
    (411, 'SW_DUCT_DIAMETER', '500', None, None, None),
    (412, 'SW_DUCT_DIAMETER', '570', None, None, None),
    (413, 'SW_DUCT_DIAMETER', '600', None, None, None),
    (414, 'SW_DUCT_DIAMETER', '700', None, None, None),
    (415, 'SW_DUCT_DIAMETER', '800', None, None, None),
    (416, 'SW_DUCT_DIAMETER', '900', None, None, None),
    (417, 'SW_DUCT_DIAMETER', '1000', None, None, None),
    (418, 'SW_DUCT_DIAMETER', '1200', None, None, None),
    (419, 'SW_DUCT_DIAMETER', '1500', None, None, None),
    (420, 'SW_DUCT_DIAMETER', '1800', None, None, None),
    (421, 'SW_DUCT_DIAMETER', '2000', None, None, None),
    (422, 'SW_DUCT_DIAMETER', '2300', None, None, None),
    (423, 'SW_DUCT_MATERIAL', 'Määramata', None, 'Kanalitoru materjal', None),
    (424, 'SW_DUCT_MATERIAL', 'Betoon', None, None, None),
    (425, 'SW_DUCT_MATERIAL', 'Teras', None, None, None),
    (426, 'SW_DUCT_MATERIAL', 'Malm', None, None, None),
    (427, 'SW_DUCT_MATERIAL', 'Moodul', None, None, None),
    (428, 'SW_DUCT_MATERIAL', 'Komposiit', None, None, None),
    (429, 'SW_DUCT_MATERIAL', 'KER', None, None, None),
    (430, 'SW_DUCT_MATERIAL', 'Sukk', None, None, None),
    (431, 'SW_DUCT_MATERIAL', 'ASB', None, None, None),
    (432, 'SW_DUCT_MATERIAL', 'PE', None, None, None),
    (433, 'SW_DUCT_MATERIAL', 'PP', None, None, None),
    (434, 'SW_DUCT_MATERIAL', 'PVC', None, None, None),
    (435, 'SW_DUCT_MATERIAL', 'PE RC', None, None, None),
    (436, 'SW_MANHOLE_DIAMETER', '200', None, 'Kanalikaevu diameeter', None),
    (437, 'SW_MANHOLE_DIAMETER', '400', None, None, None),
    (438, 'SW_MANHOLE_DIAMETER', '500', None, None, None),
    (439, 'SW_MANHOLE_DIAMETER', '600', None, None, None),
    (440, 'SW_MANHOLE_DIAMETER', '800', None, None, None),
    (441, 'SW_MANHOLE_DIAMETER', '1000', None, None, None),
    (442, 'SW_MANHOLE_DIAMETER', '1500', None, None, None),
    (443, 'SW_MANHOLE_DIAMETER', '2000', None, None, None),
    (444, 'SW_MANHOLE_DIAMETER', '2500', None, None, None),
    (445, 'SW_MANHOLE_DIAMETER', '3000', None, None, None),
    (446, 'MANHOLE_MATERIAL', 'Määramata', None, 'Kaevu materjal', None),
    (447, 'MANHOLE_MATERIAL', 'Betoon rõngas', None, None, None),
    (448, 'MANHOLE_MATERIAL', 'Betoon monoliit', None, None, None),
    (449, 'MANHOLE_MATERIAL', 'Pritsbetoon', None, None, None),
    (450, 'MANHOLE_MATERIAL', 'Tellis', None, None, None),
    (451, 'MANHOLE_MATERIAL', 'Komposiit', None, None, None),
    (452, 'MANHOLE_MATERIAL', 'Plast', None, None, None),
    (453, 'MANHOLE_MATERIAL', 'PVC', None, None, None),
    (454, 'MANHOLE_MATERIAL', 'PE', None, None, None),
    (455, 'MANHOLE_MATERIAL', 'Puit', None, None, None),
    (456, 'SW_MANHOLE_TYPE', 'Määramata', None, 'Kanali kaevu tüüp', None),
    (457, 'SW_MANHOLE_TYPE', 'Restkaev', None, None, None),
    (458, 'SW_MANHOLE_TYPE', 'Survekustutuskaev', None, None, None),
    (459, 'SW_MANHOLE_TYPE', 'Hoolduskaev', None, None, None),
    (460, 'SW_MANHOLE_TYPE', 'Astangkaev', None, None, None),
    (461, 'SW_MANHOLE_TYPE', 'Kontrollkaev', None, None, None),
    (462, 'SW_MANHOLE_TYPE', 'Kontrolltoru', None, None, None),
    (463, 'SW_MANHOLE_TYPE', 'Vaakumkaev', None, None, None),
    (464, 'SW_OTHER_NODE_TYPE', 'Määramata', None, 'Kanali muude punktobjektide tüüp', None),
    (465, 'SW_OTHER_NODE_TYPE', 'Kaitsearmatuur', None, None, None),
    (466, 'SW_OTHER_NODE_TYPE', 'Suubla', None, None, None),
    (467, 'SW_OTHER_NODE_TYPE_SUB', 'Määramata', None, 'Kanali muude punktobjektide alamtüüp', None),
    (468, 'SW_OTHER_NODE_TYPE_SUB', 'Õhueraldusklapp', None, None, None),
    (469, 'SW_OTHER_NODE_TYPE_SUB', 'Tagasilöögiklapp', None, None, None),
    (470, 'SW_PS_CONTROL', 'Määramata', None, 'Pumbajaama juhitavus', None),
    (471, 'SW_PS_CONTROL', 'Kaugjuhitav', None, None, None),
    (472, 'SW_PS_CONTROL', 'Automaatne', None, None, None),
    (473, 'SW_PS_CONTROL', 'Käsijuhtimine', None, None, None),
    (474, 'SW_PS_ROLE', 'Määramata', None, 'Pumbajaama roll', None),
    (475, 'SW_PS_ROLE', 'Liini pumbajaam', None, None, None),
    (476, 'SW_PS_ROLE', 'Vahepumbajaam', None, None, None),
    (477, 'SW_PS_ROLE', 'Peapumpla', None, None, None),
    (478, 'SW_PS_TYPE', 'Määramata', None, 'Kanalisatsioonipumpla tüüp', None),
    (479, 'SW_PS_TYPE', 'Kanalisatsiooni pumpla', None, None, None),
    (480, 'SW_PS_TYPE', 'Sademevee pumpla', None, None, None),
    (481, 'SW_PS_TYPE', 'Vaakumpumpla', None, None, None),
    (482, 'SW_PUMP_TYPE', 'Määramata', None, 'Tööratta tüüp', None),
    (483, 'SW_PUMP_TYPE', 'Ühe kanaliga', None, None, None),
    (484, 'SW_PUMP_TYPE', 'Kahe kanaliga', None, None, None),
    (485, 'SW_PUMP_TYPE', 'Kolme kanaliga', None, None, None),
    (486, 'SW_PUMP_TYPE', 'Keevis', None, None, None),
    (487, 'SW_PUMP_TYPE', 'Vortex', None, None, None),
    (488, 'SW_VALVE_TYPE', 'Määramata', None, 'Kanali sulgeseadme liik', None),
    (489, 'SW_VALVE_TYPE', 'Õhutuskraan', None, None, None),
    (490, 'SW_VALVE_TYPE', 'Siiber', None, None, None),
    (491, 'SW_VALVE_TYPE', 'Kilpsiiber', None, None, None),
    (492, 'SW_VALVE_TYPE', 'Tagasivooluklapp', None, None, None),
    (493, 'SW_VALVE_TYPE_SUB', 'Määramata', None, 'Kanali sulgeseadme alamliik', None),
    (494, 'SW_VALVE_TYPE_SUB', 'Kiil', None, None, None),
    (495, 'SW_VALVE_TYPE_SUB', 'Klapp', None, None, None),
    (496, 'TEL_CABLE_MARK', 'Määramata', None, 'Sidekaabli mark', None),
    (497, 'TEL_CABLE_MARK', 'GNHLDV 24 G652.D', None, None, None),
    (498, 'TEL_CABLE_MARK', 'OPTRAL 48 ABD', None, None, None),
    (499, 'TEL_CABLE_TYPE', 'Määramata', None, 'Sidekaabli tüüp', None),
    (500, 'TEL_CABLE_TYPE', 'Optika', None, None, None),
    (501, 'TEL_CABLE_TYPE', 'Vask', None, None, None),
    (502, 'TEL_LOCATION', 'Kaev', None, 'Paigalduskoht', None),
    (503, 'TEL_LOCATION', 'Välikapp', None, None, None),
    (504, 'TEL_LOCATION', 'Sisekapp', None, None, None),
    (505, 'TEL_LOCATION', 'Post', None, None, None),
    (506, 'TEL_NODE_GROUP', 'Jaotuskoht', None, 'Sidesõlme grupp', None),
    (507, 'TEL_NODE_GROUP', 'Võrgusõlm', None, None, None),
    (508, 'TEL_NODE_GROUP', 'Muhv', None, None, None),
    (509, 'TEL_NODE_GROUP', 'Sidekaev', None, None, None),
    (510, 'TEL_NODE_TYPE', 'VK600', 'Jaotuskoht', 'Sidesõlme alamgrupp', None),
    (511, 'TEL_NODE_TYPE', 'VK400', 'Jaotuskoht', None, None),
    (512, 'TEL_NODE_TYPE', 'VK1500', 'Jaotuskoht', None, None),
    (513, 'TEL_NODE_TYPE', 'Otsejätk', 'Muhv', None, None),
    (514, 'TEL_NODE_TYPE', 'Harujätk', 'Muhv', None, None),
    (515, 'TEL_NODE_TYPE', 'Splitter', 'Muhv', None, None),
    (516, 'TEL_NODE_TYPE', 'Sidekaev', 'Sidekaev', None, None),
    (517, 'TEL_NODE_TYPE', 'Reservkaev', 'Sidekaev', None, None),
    (518, 'USAGE_STATE', 'Kasutusel', None, 'Kasutuse olek', None),
    (519, 'USAGE_STATE', 'Planeeritud', None, None, None),
    (520, 'USAGE_STATE', 'Kasutusest kõrvaldatud', None, None, None),
    (521, 'USAGE_STATE', 'Likvideeritud', None, None, None),
    (522, 'W_BRANCH_TYPE', 'Määramata', None, 'Liitmiku tüüp', None),
    (523, 'W_BRANCH_TYPE', 'Käänik', None, None, None),
    (524, 'W_BRANCH_TYPE', 'Kaelus', None, None, None),
    (525, 'W_BRANCH_TYPE', 'Kolmik', None, None, None),
    (526, 'W_BRANCH_TYPE', 'Nelik', None, None, None),
    (527, 'W_BRANCH_TYPE', 'Liitmik', None, None, None),
    (528, 'W_BRANCH_TYPE', 'Üleminek', None, None, None),
    (529, 'W_BRANCH_TYPE', 'Äärik', None, None, None),
    (530, 'W_BRANCH_TYPE', 'Sadul', None, None, None),
    (531, 'W_BRANCH_TYPE', 'Otsakork', None, None, None),
    (532, 'W_BRANCH_TYPE_SUB', 'Määramata', None, 'Liitmiku alamtüüp', None),
    (533, 'W_BRANCH_TYPE_SUB', 'T-kolmik muhviga', None, None, None),
    (534, 'W_BRANCH_TYPE_SUB', 'T-kolmik flantsiga ', None, None, None),
    (535, 'W_BRANCH_TYPE_SUB', 'elektrikeevisliitmik', None, None, None),
    (536, 'W_DUCT_DIAMETER', '20', None, 'Veetoru diameeter', None),
    (537, 'W_DUCT_DIAMETER', '25', None, None, None),
    (538, 'W_DUCT_DIAMETER', '32', None, None, None),
    (539, 'W_DUCT_DIAMETER', '40', None, None, None),
    (540, 'W_DUCT_DIAMETER', '50', None, None, None),
    (541, 'W_DUCT_DIAMETER', '63', None, None, None),
    (542, 'W_DUCT_DIAMETER', '90', None, None, None),
    (543, 'W_DUCT_DIAMETER', '100', None, None, None),
    (544, 'W_DUCT_DIAMETER', '110', None, None, None),
    (545, 'W_DUCT_DIAMETER', '125', None, None, None),
    (546, 'W_DUCT_DIAMETER', '150', None, None, None),
    (547, 'W_DUCT_DIAMETER', '160', None, None, None),
    (548, 'W_DUCT_DIAMETER', '180', None, None, None),
    (549, 'W_DUCT_DIAMETER', '200', None, None, None),
    (550, 'W_DUCT_DIAMETER', '225', None, None, None),
    (551, 'W_DUCT_DIAMETER', '250', None, None, None),
    (552, 'W_DUCT_DIAMETER', '300', None, None, None),
    (553, 'W_DUCT_DIAMETER', '350', None, None, None),
    (554, 'W_DUCT_DIAMETER', '400', None, None, None),
    (555, 'W_DUCT_MATERIAL', 'Määramata', None, 'Veetoru materjal', None),
    (556, 'W_DUCT_MATERIAL', 'Malm', None, None, None),
    (557, 'W_DUCT_MATERIAL', 'Teras', None, None, None),
    (558, 'W_DUCT_MATERIAL', 'Sukk', None, None, None),
    (559, 'W_DUCT_MATERIAL', 'PE', None, None, None),
    (560, 'W_DUCT_MATERIAL', 'PVC', None, None, None),
    (561, 'W_DUCT_MATERIAL', 'PE RC', None, None, None),
    (562, 'W_MANHOLE_DIAMETER', '400', None, 'Veekaevu diameeter', None),
    (563, 'W_MANHOLE_DIAMETER', '560', None, None, None),
    (564, 'W_MANHOLE_DIAMETER', '700', None, None, None),
    (565, 'W_MANHOLE_DIAMETER', '1000', None, None, None),
    (566, 'W_MANHOLE_DIAMETER', '1500', None, None, None),
    (567, 'W_MANHOLE_DIAMETER', '2000', None, None, None),
    (568, 'W_MANHOLE_DIAMETER', '2500', None, None, None),
    (569, 'W_MANHOLE_DIAMETER', '3000', None, None, None),
    (570, 'W_MANHOLE_TYPE', 'Määramata', None, 'Vee seadmekaev', None),
    (571, 'W_MANHOLE_TYPE', 'Arvestikaev', None, None, None),
    (572, 'W_MANHOLE_TYPE', 'Hoolduskaev', None, None, None),
    (573, 'W_MANHOLE_TYPE', 'Läbipesusõlm', None, None, None),
    (574, 'W_OTHER_NODE_TYPE', 'Määramata', None, 'Vee muude punktobjektide tüüp', None),
    (575, 'W_OTHER_NODE_TYPE', 'Kaitsearmatuur', None, None, None),
    (576, 'W_OTHER_NODE_TYPE', 'Veetöötlusjaam', None, None, None),
    (577, 'W_OTHER_NODE_TYPE_SUB', 'Määramata', None, 'Vee muude punktobjektide alamtüüp', None),
    (578, 'W_OTHER_NODE_TYPE_SUB', 'Õhueraldi', None, None, None),
    (579, 'W_OTHER_NODE_TYPE_SUB', 'Tagasilöögiklapp', None, None, None),
    (580, 'W_OTHER_NODE_TYPE_SUB', 'Ülerõhuklapp', None, None, None),
    (581, 'W_PRESSURE_STATION_TYPE', 'Reguleerimissõlm', None, 'Reguleerimissõlme tüüp', None),
    (582, 'W_PRESSURE_STATION_TYPE_SUB', 'Survetõste pumpla', None, 'Reguleerimissõlme alamtüüp', None),
    (583, 'W_PRESSURE_STATION_TYPE_SUB', 'Rõhu alandamine', None, None, None),
    (584, 'W_PRESSURE_STATION_TYPE_SUB', 'Hüdrofoor', None, None, None),
    (585, 'W_PUMP_TYPE', 'Määramata', None, 'Veepumba tüüp', None),
    (586, 'W_TANK_TYPE', 'Määramata', None, 'Veemahuti tüüp', None),
    (587, 'W_TANK_TYPE', 'Veetorn', None, None, None),
    (588, 'W_TANK_TYPE', 'Veepaak', None, None, None),
    (589, 'W_VALVE_TYPE', 'Liini', None, 'Vee sulgeseadme liik', None),
    (590, 'W_VALVE_TYPE', 'Kinnistu', None, None, None),
    (591, 'W_VALVE_TYPE_SUB', 'Määramata', None, 'Vee sulgeseadme alamliik', None),
    (592, 'W_VALVE_TYPE_SUB', 'Kiil', None, None, None),
    (593, 'W_VALVE_TYPE_SUB', 'Klapp', None, None, None),
    (594, 'W_VALVE_TYPE_SUB', 'Kummikiil', None, None, None),
    (595, 'W_VALVE_TYPE_SUB', 'Kuulkraan', None, None, None),
    (596, 'W_VALVE_TYPE_SUB', 'Korkkraan', None, None, None),
    (597, 'W_VALVE_TYPE_SUB', 'Vene malm', None, None, None),
    (598, 'VALVE_HAND', 'Määramata', None, 'Sulgeseadme käelisus', None),
    (599, 'VALVE_HAND', 'Parem', None, None, None),
    (600, 'VALVE_HAND', 'Vasak', None, None, None),
    (601, 'VOLTAGE', 'Määramata', None, 'Pinge', None),
    (602, 'VOLTAGE', '230', None, None, None),
    (603, 'VOLTAGE', '400', None, None, None),
    (604, 'VOLTAGE', '1000', None, None, None),
    (605, 'VOLTAGE', '5000', None, None, None)
    }
