# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kalver\Desktop\Plugins\mailabl-qgis\mailabl-qgis\Functions\Easements\widgets\Servituut.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_servituutDialogBase(object):
    def setupUi(self, servituutDialogBase):
        servituutDialogBase.setObjectName("servituutDialogBase")
        servituutDialogBase.setEnabled(True)
        servituutDialogBase.resize(900, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(servituutDialogBase.sizePolicy().hasHeightForWidth())
        servituutDialogBase.setSizePolicy(sizePolicy)
        servituutDialogBase.setMinimumSize(QtCore.QSize(900, 750))
        servituutDialogBase.setMaximumSize(QtCore.QSize(900, 750))
        servituutDialogBase.setStyleSheet("\n"
"#lblDialer{\n"
"    background-color: None;\n"
"    backround: None;\n"
"    border: None\n"
"}\n"
"\n"
"\n"
"\n"
"*{\n"
"    border: transparent;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #c5c5d2;\n"
"}\n"
"\n"
"\n"
"QWidget{\n"
"    background-color: #272c35;\n"
"    color:#c5c5d2\n"
"}\n"
"\n"
"\n"
"/*Line Edit styling*/\n"
"QLineEdit {\n"
"    background-color: #35363f;  /* Lighter background color */\n"
"    color: #ececf1;\n"
"    /*border: 1px solid #4d4d5b;  Thinner border with a different color */\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #3d3e47;  /* Slightly darker background color on hover */\n"
"}\n"
"\n"
"/* Remove top and side borders */\n"
"QLineEdit {\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"\n"
"/*konteinerite peamised omadused*/\n"
"#centerMenuSubContainer{\n"
"    background-color: #272c35;\n"
"}\n"
"\n"
"#swWorkSpace{\n"
"    background-color: #202123;\n"
"}\n"
"#Sevituudid{\n"
"    background-color: #343b47;\n"
"}\n"
"\n"
"#leftMenuContainer{\n"
"    background-color: #202123 ;\n"
"}\n"
"\n"
"#rightMenuContainer{\n"
"    background-color: #272c35;\n"
"}\n"
"\n"
"#SetupLayers, #SetupLayers_2, #SetupUserData {\n"
"border: none;\n"
"border-bottom: 1px solid rgb(131, 142, 162);\n"
"}\n"
"\n"
"/*nuppu peamised omadused*/\n"
"/*Üldomadused*/\n"
"QPushButton{\n"
"    padding: 1px 5px;\n"
"    text-align: center;\n"
"    border-radius: 5px;\n"
"    background-color:#40414f;\n"
"    border: 1px solid #565869;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8e8ea0;\n"
"    border: 0.5px solid #acacbe;\n"
"    color: #343541;\n"
"    text-align: center;\n"
"    padding: 2px 5px;\n"
"    border-radius: 5px;    \n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #303040; /* Adjusted disabled background color */\n"
"    border: 1px solid #707070; /* Adjust border color for disabled state */\n"
"    color: #8a95a5; /* Adjust text color for disabled state */\n"
"}\n"
"\n"
"\n"
"#UC_Main_Frame QPushButton,#pbChoose_Properties_for_Projects{\n"
"    padding: 1px 8px;\n"
"    border-radiusr: 6px;\n"
"}\n"
"\n"
"#UC_Main_Frame QPushButton:hover{\n"
"\n"
"    padding: 1px 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"#wOl_Settings QPushButton{\n"
"    padding: 1px 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#wOl_Settings QPushButton:hover{\n"
"    padding: 1px 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#rightMenuContainer QPushButton{\n"
"    text-align: right;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    \n"
"}\n"
"\n"
"#rightMenuContainer QPushButton:hover{\n"
"    text-align: right;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;  \n"
"}\n"
"\n"
"\n"
"#leftMenuContainer QPushButton{\n"
"    text-align: left;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;    \n"
"}\n"
"#leftMenuContainer QPushButton:hover{\n"
"    text-align: left;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* Combined Style for QComboBox to Ensure Consistency */\n"
"\n"
"/* Base style for QComboBox */\n"
"QComboBox {\n"
"    border: 1px solid #565869; /* Using --gray-600 */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    background-color: #343541; /* Using --gray-800 */\n"
"    color: #ececf1; /* Using --gray-100 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QComboBox:disabled {\n"
"    background-color: #c5c5d2; /* Using --gray-300 */\n"
"    color: #8e8ea0; /* Using --gray-500 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Hover state */\n"
"QComboBox:hover {\n"
"    border: 1px solid #acacbe; /* Using --gray-400 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Focus state */\n"
"QComboBox:focus {\n"
"    border: 1px solid #acacbe; /* Kept original lime green color */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Dropdown button */\n"
"QComboBox::drop-down {\n"
"    subcontrol-position: center right;\n"
"    border-radius: 3px; /* Rounded corners */\n"
"    /*width: 24px;*/\n"
"    borde: 0.5px solid #acacbe; /* Kept original lime green color */\n"
"    background-color: #343541; /* Using --gray-800 */\n"
"}\n"
"\n"
"/* Dropdown arrow */\n"
"QComboBox::down-arrow {\n"
"    image: url(\':/qt-project.org/styles/macstyle/images/toolbar-ext.png\'); /* Default arrow image */\n"
"    height: 16px;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(\':/qt-project.org/styles/macstyle/images/toolbar-ext.png\'); /* Arrow image on hover, focus */\n"
"}\n"
"\n"
"/* QAbstractItemView (dropdown list) */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #343541; /* Using --gray-900 */\n"
"    border: 1px solid #4d4d4d; /* Similar to gray-600 */\n"
"    selection-background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgba(50, 50, 50, 255), /* Dark gray */\n"
"        stop: 1 rgba(100, 100, 100, 255) /* Lighter gray */\n"
"    );\n"
"    selection-color: #ececf1; /* Using --gray-100 */\n"
"    color: #ececf1;\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Selected item in list */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgba(50, 50, 50, 255), /* Dark gray */\n"
"        stop: 1 rgba(100, 100, 100, 255) /* Lighter gray */\n"
"    );\n"
"    color: #ececf1; /* Using --gray-100 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Hover over item in list */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgba(50, 50, 50, 255), /* Dark gray */\n"
"        stop: 1 rgba(100, 100, 100, 255) /* Lighter gray */\n"
"    );\n"
"    color: #ececf1; /* Using --gray-100 */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Handle the padding of items in the list view */\n"
"QComboBox QAbstractItemView::item {\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Ensure keyboard navigation shows selection */\n"
"QComboBox::item:selected:!hover {\n"
"    background-color: qlineargradient(\n"
"        spread: pad, \n"
"        x1: 0, y1: 0, \n"
"        x2: 0, y2: 1, \n"
"        stop: 0.259887 rgba(50, 50, 50, 202), \n"
"        stop: 1 rgba(180, 180, 180, 255)\n"
"    ); \n"
"    color: #ececf1; /* White text color for keyboard selection */\n"
"    padding-left: 2px; /* Move text 2 pixels to the right */\n"
"}\n"
"\n"
"/* Checked state of the checkbox */\n"
"QComboBox::indicator:checked {\n"
"    background-color: #565869; /* Kept original lime green color */\n"
"    image: url(\':/images/themes/default/algorithms/mAlgorithmCheckGeometry.svg\'); /* Path to your checked image */\n"
"    width: 10px;  /* Adjusted width to fit within the border */\n"
"    height: 10px; /* Adjusted height to fit within the border */\n"
"}\n"
"\n"
"/* Unchecked state can have a background color */\n"
"QComboBox::indicator:unchecked {\n"
"    background-color: #565869; /* Using --gray-600 */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* General QCheckBox styles */\n"
"QCheckBox {\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"    spacing: 5px; /* Space between checkbox and text */\n"
"}\n"
"\n"
"/* Style the indicator (checkbox) */\n"
"QCheckBox::indicator {\n"
"    width: 12px; /* Width of the checkbox */\n"
"    height: 12px; /* Height of the checkbox */\n"
"    background-color: #3a3b46; /* Darker gray for unchecked state */\n"
"    border: 1px solid #565869; /* Border color for unchecked state */\n"
"    border-radius: 2px; /* Slightly rounded corners */\n"
"}\n"
"\n"
"/* Style the indicator when checked */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #4a4b59; /* Slightly darker gray for checked state */\n"
"    border: 1px solid #4d4d4d; /* Border color matching the theme */\n"
"    border-radius: 2px; /* Slightly rounded corners */\n"
"    image: url(:/images/themes/default/algorithms/mAlgorithmCheckGeometry.svg); /* Using provided SVG icon URL */\n"
"}\n"
"\n"
"/* Style the indicator when unchecked */\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: #3a3b46; /* Darker gray for unchecked state */\n"
"    border: 1px solid #565869; /* Border color for unchecked state */\n"
"}\n"
"\n"
"/* Style the indicator when hovered */\n"
"QCheckBox::indicator:hover {\n"
"    background-color: #4e4f5b; /* Medium gray when hovering */\n"
"}\n"
"\n"
"/* Style the indicator when disabled */\n"
"QCheckBox::indicator:disabled {\n"
"    background-color: #30303a; /* Darker background color for disabled state */\n"
"    border: 1px solid #4d4d4d; /* Darker border for disabled state */\n"
"}\n"
"\n"
"/* Style the indicator when checked and disabled */\n"
"QCheckBox::indicator:checked:disabled {\n"
"    background-color: rgba(50, 50, 60, 0.5); /* Semi-transparent darker gray for checked and disabled state */\n"
"    border: 1px solid #4d4d4d; /* Border color matching the theme */\n"
"    image: url(:/images/themes/default/algorithms/mAlgorithmCheckGeometry.svg); /* Using provided SVG icon URL */\n"
"    opacity: 0.5; /* Make the icon appear disabled */\n"
"}\n"
"\n"
"/* Style the checkbox text when disabled */\n"
"QCheckBox:disabled {\n"
"    color: #6a6a75; /* Darker text color for disabled state */\n"
"}\n"
"\n"
"\n"
"QGroupBox{\n"
"    color: #ececf1;\n"
"}\n"
"\n"
"\n"
"/* Style for the selected tab */\n"
"QTabBar::tab:selected {\n"
"    background-color: #50515f; /* Background color for the selected tab */\n"
"    color: #ececf1; /* Text color for the selected tab */\n"
"    border: 1px solid #acacbe; /* Lighter border for the selected tab */\n"
"    border-bottom: 1px solid #202123; /* Match the background color of the tab pane to create a seamless look */\n"
"    padding: 7px 12px; /* Slightly adjust padding for selected tab */\n"
"}\n"
"\n"
"/* Style for the hovered tab */\n"
"QTabBar::tab:hover {\n"
"    background-color: #8e8ea0; /* Background color when hovering over a tab */\n"
"    color: #343541; /* Text color for the hovered tab */\n"
"    border: 1px solid #acacbe; /* Lighter border on hover */\n"
"}\n"
"\n"
"/* Style for disabled tabs */\n"
"QTabBar::tab:disabled {\n"
"    background-color: #30303a; /* Darker background for disabled tabs */\n"
"    color: #6a6a75; /* Muted text color for disabled tabs */\n"
"    border: 1px solid #565869; /* Border color for disabled tabs */\n"
"}\n"
"\n"
"/* Adjustments to the tab pane (content area below the tabs) */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #565869; /* Border around the content area */\n"
"    background-color: #202123; /* Match the background of the content area to other containers */\n"
"    border-radius: 3px; /* Rounded corners for the content area */\n"
"    margin-top: -1px; /* Overlap with the tab bar to create a seamless transition */\n"
"}\n"
"\n"
"/* General QScrollBar style within QTableView */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: transparent; /* Ensure the scrollbar background is transparent */\n"
"}\n"
"\n"
"/* Vertical scroll bar groove (track) */\n"
"QScrollBar::groove:vertical {\n"
"    border: 1px solid #4d4d4d; /* Dark border around the groove */\n"
"    width: 8px; /* Width of the groove */\n"
"    background: #333; /* Darker gray for the groove background */\n"
"    border-radius: 3px; /* Adjusted to be less than half of 8px */\n"
"}\n"
"\n"
"/* Horizontal scroll bar groove (track) */\n"
"QScrollBar::groove:horizontal {\n"
"    border: 1px solid #4d4d4d; /* Dark border around the groove */\n"
"    height: 8px; /* Height of the groove */\n"
"    background: #333; /* Darker gray for the groove background */\n"
"    border-radius: 3px; /* Adjusted to be less than half of 8px */\n"
"}\n"
"\n"
"/* Vertical scroll bar handle (thumb) */\n"
"QScrollBar::handle:vertical {\n"
"    background: #b5b5b5; /* Lighter gray for the handle */\n"
"    border: 1px solid #707070; /* Slightly darker border for the handle */\n"
"    width: 16px; /* Width of the handle */\n"
"    border-radius: 6px; /* Adjusted to be less than half of 16px for a rounded effect */\n"
"}\n"
"\n"
"/* Horizontal scroll bar handle (thumb) */\n"
"QScrollBar::handle:horizontal {\n"
"    background: #b5b5b5; /* Lighter gray for the handle */\n"
"    border: 1px solid #707070; /* Slightly darker border for the handle */\n"
"    height: 16px; /* Height of the handle */\n"
"    border-radius: 6px; /* Adjusted to be less than half of 16px for a rounded effect */\n"
"}\n"
"\n"
"/* Handle when hovered (both vertical and horizontal) */\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background: #d8d8d8; /* Lighter gray when hovered */\n"
"}\n"
"\n"
"/* Handle when pressed (both vertical and horizontal) */\n"
"QScrollBar::handle:vertical:pressed, QScrollBar::handle:horizontal:pressed {\n"
"    background: #999; /* Darker gray when pressed */\n"
"}\n"
"\n"
"/* Slider groove when focused (both vertical and horizontal) */\n"
"QScrollBar::groove:vertical:focus, QScrollBar::groove:horizontal:focus {\n"
"    background: #444; /* Slightly brighter when focused */\n"
"}\n"
"\n"
"/* Scrollbar arrows (both vertical and horizontal) */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: #40414f; /* Background for the arrows */\n"
"    border: 1px solid #565869; /* Border for the arrows */\n"
"    border-radius: 2px; /* Adjusted to be less than half of 4px */\n"
"}\n"
"\n"
"/* Arrows on hover */\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::sub-line:vertical:hover,\n"
"QScrollBar::add-line:horizontal:hover, QScrollBar::sub-line:horizontal:hover {\n"
"    background: #8e8ea0; /* Lighter background on hover */\n"
"}\n"
"\n"
"/* Style for the scroll bar pages (scroll bar track) */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none; /* No background for the pages */\n"
"}\n"
"\n"
"/* Adjust QListWidget style */\n"
"QListWidget {\n"
"    background-color: #2e2f38; /* Dark gray background to match the new theme */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"    border: 1px solid #4d4d4d; /* Border color matching the scrollbar groove */\n"
"    border-radius: 3px; /* Rounded corners */\n"
"    padding: 3px; /* Add padding to the list */\n"
"}\n"
"\n"
"/* Style for individual items in the QListWidget */\n"
"QListWidget::item {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 rgba(60, 62, 73, 0.2), stop: 1 rgba(42, 42, 51, 0.35)); /* Gradient for non-selected items */\n"
"    color: #d1d1e0; /* Light gray text color for unselected items */\n"
"    padding: 3px; /* Padding around list items */\n"
"    border-radius: 1.5px; /* Slight rounding of the item edges */\n"
"}\n"
"\n"
"/* Style for selected items in QListWidget */\n"
"QListWidget::item:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 rgba(210, 72, 72, 0.05), stop: 1 rgba(210, 72, 72, 0.25)); /* Gradient for selected items */\n"
"    color: #ececf1; /* Lighter text color for selected items */\n"
"    border: 1px solid #707070; /* Lighter border for the selected item */\n"
"}\n"
"\n"
"/* Style for hovered items in QListWidget */\n"
"QListWidget::item:hover {\n"
"    background-color: #4e4f5b; /* Medium gray background color when hovering */\n"
"    color: #ececf1; /* Text color on hover to maintain contrast */\n"
"}\n"
"\n"
"/* Style for disabled items in QListWidget */\n"
"QListWidget::item:disabled {\n"
"    background-color: #30303a; /* Darker background for disabled items */\n"
"    color: #6a6a75; /* Muted gray text color for disabled items */\n"
"}\n"
"\n"
"/* General QLineEdit styles */\n"
"QLineEdit {\n"
"    background-color: #35363f; /* Lighter background color */\n"
"    color: #ececf1; /* Light gray text color */\n"
"    border: 1px solid #4d4d5b; /* Thinner border with a different color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 4px; /* Padding inside the line edit */\n"
"    /* Remove top and side borders */\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"/* Style for the line edit when focused */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #6a6a75; /* Highlight border color when focused */\n"
"    background-color: #35363f; /* Keep the background color consistent when focused */\n"
"}\n"
"\n"
"/* Style for the placeholder text */\n"
"QLineEdit::placeholder {\n"
"    color: #6a6a75; /* Lighter gray color for placeholder text */\n"
"}\n"
"\n"
"/* Style for the line edit when disabled */\n"
"QLineEdit:disabled {\n"
"    background-color: #30303a; /* Darker background color for disabled state */\n"
"    color: #6a6a75; /* Muted gray text color for disabled state */\n"
"    border: 1px solid #4d4d4d; /* Same border color as normal state */\n"
"}\n"
"\n"
"/* Style for the line edit when read-only */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #35363f; /* Same as normal background */\n"
"    color: #ececf1; /* Same as normal text color */\n"
"    border: 1px solid #4d4d5b; /* Same as normal border */\n"
"    border-style: dashed; /* Dashed border style for read-only state */\n"
"}\n"
"\n"
"/* Style for the line edit when active */\n"
"QLineEdit:active {\n"
"    border: 1px solid #6a6a75; /* Highlight border color when active */\n"
"}\n"
"\n"
"/* Style for the line edit when hovered */\n"
"QLineEdit:hover {\n"
"    background-color: #3d3e47; /* Slightly darker background color on hover */\n"
"}\n"
"\n"
"/* Style for the line edit when error state (optional) */\n"
"QLineEdit:invalid {\n"
"    border: 1px solid #d20000; /* Red border for invalid input */\n"
"}\n"
"\n"
"/* Style for the line edit when modified (optional) */\n"
"QLineEdit:modified {\n"
"    border: 1px solid #d1d1e0; /* Border color indicating modification */\n"
"}\n"
"\n"
"\n"
"/* General QTableView adjustments */\n"
"QTableView {\n"
"    background-color: #2e2f38; /* Dark gray for all rows */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"    border: 1px solid #4d4d4d; /* Border color matching the scrollbar groove */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    gridline-color: #565869; /* Gridline color */\n"
"    selection-background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgba(46, 47, 56, 10),   /* Lighter gray with higher transparency (about 47%) */\n"
"        stop: 1 rgba(210, 72, 72, 50)    /* Darker red with lower transparency (about 29%) */\n"
"    ); /* Gradient for selected cells */\n"
"    selection-color: #ececf1; /* Lighter text color for selected cells */\n"
"}\n"
"\n"
"/* Adjust header style */\n"
"QHeaderView::section {\n"
"    background-color: #35353f; /* Darker gray background for the header */\n"
"    color: #d1d1e0; /* Light gray text color in the header */\n"
"    border-top: 0.5px solid #323232; /* Slightly darker border on top */\n"
"    border-left: 0.5px solid #323232; /* Slightly darker border on left */\n"
"    border-right: 0.5px solid #323232; /* Slightly darker border on right */\n"
"    border-bottom: 1px solid #4d4d4d; /* Lighter bottom border to separate data from headers */\n"
"    padding: 1px 3px; /* Slightly reduced padding */\n"
"    border-top-left-radius: 2px; /* Retain rounding on the top-left corner */\n"
"    border-top-right-radius: 2px; /* Retain rounding on the top-right corner */\n"
"    border-bottom-left-radius: 0px; /* No rounding on the bottom-left corner */\n"
"    border-bottom-right-radius: 0px; /* No rounding on the bottom-right corner */\n"
"    font-size: 11px; /* Reduced font size */\n"
"}\n"
"\n"
"/* Style for hovered rows */\n"
"QTableView::item:hover {\n"
"    background-color: #4e4f5b; /* Medium gray background color when hovering over a row */\n"
"    color: #ececf1; /* Text color on hover for better contrast */\n"
"}\n"
"\n"
"/* Style for selected rows */\n"
"QTableView::item:selected {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgba(46, 47, 56, 10),   /* Lighter gray with higher transparency (about 47%) */\n"
"        stop: 1 rgba(210, 72, 72, 50)    /* Darker red with lower transparency (about 29%) */\n"
"    ); /* Gradient background color for selected rows */\n"
"    color: #ececf1; /* Light gray text color for selected rows */\n"
"}\n"
"\n"
"/* Style for all rows (non-selected) */\n"
"QTableView::item {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgba(80, 80, 80, 25),   /* Lighter gray with 20% opacity (2 steps lighter) */\n"
"        stop: 1 rgba(42, 42, 51, 255)    /* Darker gray with 35% opacity */\n"
"    ); /* Gradient background color for non-selected rows */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"}\n"
"\n"
"/* Ensure deselected rows return to their original state */\n"
"QTableView::item:!selected {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgba(80, 80, 80, 25),   /* Lighter gray with 20% opacity (2 steps lighter) */\n"
"        stop: 1 rgba(42, 42, 51, 255)    /* Darker gray with 35% opacity */\n"
"    ); /* Reset to the default background color */\n"
"    color: #d1d1e0; /* Reset to the default text color */\n"
"}\n"
"\n"
"\n"
"/* General style for QProgressBar */\n"
"QProgressBar {\n"
"    background-color: #2e2f38; /* Dark gray background matching the table */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"    border: 1px solid #4d4d4d; /* Border matching the table border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    text-align: center; /* Center the text inside the progress bar */\n"
"    padding: 2px; /* Padding for better spacing */\n"
"}\n"
"\n"
"/* Style for the progress chunk */\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #d14848, /* Start with darker red matching the selection color */\n"
"        stop: 1 #e57373  /* End with a slightly lighter red */\n"
"    ); /* Gradient effect for the progress bar */\n"
"    border-radius: 3px; /* Slight rounding of the progress chunk */\n"
"}\n"
"\n"
"/* Style for the indeterminate progress bar (if used) */\n"
"QProgressBar[minimum=\"0\"][maximum=\"0\"] {\n"
"    background-color: #2e2f38; /* Dark gray background matching the table */\n"
"    border: 1px solid #4d4d4d; /* Border matching the table border */\n"
"    color: #d1d1e0; /* Light gray text color */\n"
"}\n"
"\n"
"QProgressBar[minimum=\"0\"][maximum=\"0\"]::chunk {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #d14848, /* Start with darker red */\n"
"        stop: 1 #e57373  /* End with a slightly lighter red */\n"
"    ); /* Moving gradient for the indeterminate progress bar */\n"
"}\n"
"\n"
"/* General QGroupBox Styling */\n"
"QGroupBox {\n"
"    color: #ececf1; /* Light gray text color for the group box title */\n"
"    background-color: #272c35; /* Dark background to match the surrounding theme */\n"
"    border: 1px solid #565869; /* Border color to distinguish the group box */\n"
"    border-radius: 5px; /* Rounded corners for a smoother look */\n"
"    margin-top: 10px; /* Space above the group box title */\n"
"    padding: 10px; /* Padding inside the group box to space out contents */\n"
"}\n"
"\n"
"/* Title of the QGroupBox */\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin; /* Align the title relative to the group box\'s margin */\n"
"    subcontrol-position: top left; /* Position the title at the top left */\n"
"    padding-left: 5px; /* Add padding to the left of the title */\n"
"    padding-right: 5px; /* Add padding to the right of the title */\n"
"    background-color: #343b47; /* Background for the title to make it stand out */\n"
"    color: #ececf1; /* Text color for the title */\n"
"    border-radius: 3px; /* Slightly round the corners of the title background */\n"
"    font-weight: bold; /* Make the title text bold */\n"
"}\n"
"\n"
"/* QGroupBox when hovered */\n"
"QGroupBox:hover {\n"
"    border: 1px solid #8e8ea0; /* Lighter border color on hover */\n"
"}\n"
"\n"
"/* QGroupBox when focused */\n"
"QGroupBox:focus {\n"
"    border: 1px solid #acacbe; /* Even lighter border color when focused */\n"
"    box-shadow: 0 0 5px 1px #8e8ea0; /* Add a subtle shadow to indicate focus */\n"
"}\n"
"\n"
"/* Disabled QGroupBox */\n"
"QGroupBox:disabled {\n"
"    color: #6a6a75; /* Darker gray text color when disabled */\n"
"    background-color: #30303a; /* Slightly darker background for disabled state */\n"
"    border: 1px solid #4d4d4d; /* Darker border color for disabled state */\n"
"}\n"
"\n"
"QGroupBox::title:disabled {\n"
"    color: #6a6a75; /* Darker title text color when disabled */\n"
"    background-color: #3a3b46; /* Darker title background color for disabled state */\n"
"}\n"
"\n"
"/* Content inside the QGroupBox */\n"
"QGroupBox QWidget {\n"
"    background-color: #2e2f38; /* Match background of content to group box */\n"
"    color: #d1d1e0; /* Light gray text color for contents */\n"
"}\n"
"")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(servituutDialogBase)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fMain = QtWidgets.QFrame(servituutDialogBase)
        self.fMain.setMinimumSize(QtCore.QSize(0, 200))
        self.fMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fMain.setObjectName("fMain")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fMain)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fMainTools = QtWidgets.QFrame(self.fMain)
        self.fMainTools.setStyleSheet("")
        self.fMainTools.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fMainTools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fMainTools.setObjectName("fMainTools")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.fMainTools)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.fSelectedItem = QtWidgets.QFrame(self.fMainTools)
        self.fSelectedItem.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fSelectedItem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fSelectedItem.setObjectName("fSelectedItem")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fSelectedItem)
        self.horizontalLayout_3.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fItemSelections = QtWidgets.QFrame(self.fSelectedItem)
        self.fItemSelections.setMinimumSize(QtCore.QSize(0, 100))
        self.fItemSelections.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fItemSelections.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fItemSelections.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fItemSelections.setObjectName("fItemSelections")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fItemSelections)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3.addWidget(self.fItemSelections)
        self.frame_3 = QtWidgets.QFrame(self.fSelectedItem)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 180))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_11.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.leInfo = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.leInfo.setFont(font)
        self.leInfo.setReadOnly(True)
        self.leInfo.setObjectName("leInfo")
        self.verticalLayout_11.addWidget(self.leInfo)
        self.lSelectedEasment = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lSelectedEasment.setFont(font)
        self.lSelectedEasment.setObjectName("lSelectedEasment")
        self.verticalLayout_11.addWidget(self.lSelectedEasment)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.leSelectedProperties = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.leSelectedProperties.setFont(font)
        self.leSelectedProperties.setReadOnly(True)
        self.leSelectedProperties.setObjectName("leSelectedProperties")
        self.verticalLayout_5.addWidget(self.leSelectedProperties)
        self.tvProperties = QtWidgets.QTableView(self.frame)
        self.tvProperties.setObjectName("tvProperties")
        self.verticalLayout_5.addWidget(self.tvProperties)
        self.verticalLayout_11.addWidget(self.frame)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(self.fSelectedItem)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout.setContentsMargins(0, 18, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbValiKinnistu = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbValiKinnistu.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../../icons/iconoir--map-pin-plus_asukoht.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbValiKinnistu.setIcon(icon)
        self.pbValiKinnistu.setIconSize(QtCore.QSize(18, 18))
        self.pbValiKinnistu.setObjectName("pbValiKinnistu")
        self.verticalLayout.addWidget(self.pbValiKinnistu)
        self.label = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dPuhvriSuurus = QtWidgets.QDial(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dPuhvriSuurus.sizePolicy().hasHeightForWidth())
        self.dPuhvriSuurus.setSizePolicy(sizePolicy)
        self.dPuhvriSuurus.setObjectName("dPuhvriSuurus")
        self.verticalLayout.addWidget(self.dPuhvriSuurus)
        self.pbClearCadastrals = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbClearCadastrals.setFont(font)
        self.pbClearCadastrals.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../../icons/Icons_hele/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClearCadastrals.setIcon(icon1)
        self.pbClearCadastrals.setIconSize(QtCore.QSize(16, 16))
        self.pbClearCadastrals.setObjectName("pbClearCadastrals")
        self.verticalLayout.addWidget(self.pbClearCadastrals)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_9.addWidget(self.fSelectedItem, 0, QtCore.Qt.AlignTop)
        self.TestValues = QtWidgets.QFrame(self.fMainTools)
        self.TestValues.setMinimumSize(QtCore.QSize(0, 100))
        self.TestValues.setMaximumSize(QtCore.QSize(16777215, 100))
        self.TestValues.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TestValues.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TestValues.setObjectName("TestValues")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TestValues)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.TestValues)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_15.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_12 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_10.addWidget(self.lineEdit_3)
        self.lblDeK = QtWidgets.QLineEdit(self.frame_12)
        self.lblDeK.setMinimumSize(QtCore.QSize(60, 0))
        self.lblDeK.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblDeK.setObjectName("lblDeK")
        self.horizontalLayout_10.addWidget(self.lblDeK)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_11.setFrame(True)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_10.addWidget(self.lineEdit_11)
        self.verticalLayout_15.addWidget(self.frame_12)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_15.addWidget(self.lineEdit_5)
        self.lblHK = QtWidgets.QLineEdit(self.frame_5)
        self.lblHK.setMinimumSize(QtCore.QSize(90, 0))
        self.lblHK.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblHK.setObjectName("lblHK")
        self.horizontalLayout_15.addWidget(self.lblHK)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_8.setFrame(True)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_15.addWidget(self.lineEdit_8)
        self.verticalLayout_15.addWidget(self.frame_5)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.TestValues)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_11.addWidget(self.lineEdit_2)
        self.lblDeV = QtWidgets.QLineEdit(self.frame_7)
        self.lblDeV.setMinimumSize(QtCore.QSize(90, 0))
        self.lblDeV.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblDeV.setObjectName("lblDeV")
        self.horizontalLayout_11.addWidget(self.lblDeV)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_7.setFrame(True)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_12.addWidget(self.lineEdit_7)
        self.lblHV = QtWidgets.QLineEdit(self.frame_8)
        self.lblHV.setMinimumSize(QtCore.QSize(90, 0))
        self.lblHV.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblHV.setObjectName("lblHV")
        self.horizontalLayout_12.addWidget(self.lblHV)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_10.setFrame(True)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_12.addWidget(self.lineEdit_10)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.horizontalLayout_9.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.TestValues)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_14.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_9 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_4.setFrame(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_13.addWidget(self.lineEdit_4)
        self.lblDeSK = QtWidgets.QLineEdit(self.frame_9)
        self.lblDeSK.setMinimumSize(QtCore.QSize(90, 0))
        self.lblDeSK.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblDeSK.setObjectName("lblDeSK")
        self.horizontalLayout_13.addWidget(self.lblDeSK)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_12.setFrame(True)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_13.addWidget(self.lineEdit_12)
        self.verticalLayout_14.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_6.setFrame(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_14.addWidget(self.lineEdit_6)
        self.lblHSK = QtWidgets.QLineEdit(self.frame_10)
        self.lblHSK.setMinimumSize(QtCore.QSize(90, 0))
        self.lblHSK.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblHSK.setObjectName("lblHSK")
        self.horizontalLayout_14.addWidget(self.lblHSK)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_9.setFrame(True)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_14.addWidget(self.lineEdit_9)
        self.verticalLayout_14.addWidget(self.frame_10)
        self.horizontalLayout_9.addWidget(self.groupBox_6)
        self.verticalLayout_9.addWidget(self.TestValues)
        self.fBaseSetup = QtWidgets.QFrame(self.fMainTools)
        self.fBaseSetup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fBaseSetup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fBaseSetup.setObjectName("fBaseSetup")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fBaseSetup)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.fBaseSetup)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cbK = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbK.setChecked(False)
        self.cbK.setObjectName("cbK")
        self.verticalLayout_8.addWidget(self.cbK)
        self.cbKSK = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbKSK.setCheckable(True)
        self.cbKSK.setChecked(False)
        self.cbKSK.setObjectName("cbKSK")
        self.verticalLayout_8.addWidget(self.cbKSK)
        self.cbsewagePupming = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbsewagePupming.setCheckable(True)
        self.cbsewagePupming.setObjectName("cbsewagePupming")
        self.verticalLayout_8.addWidget(self.cbsewagePupming)
        self.cbSewageDump = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbSewageDump.setCheckable(True)
        self.cbSewageDump.setObjectName("cbSewageDump")
        self.verticalLayout_8.addWidget(self.cbSewageDump)
        self.cbsewagePlant = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbsewagePlant.setCheckable(True)
        self.cbsewagePlant.setObjectName("cbsewagePlant")
        self.verticalLayout_8.addWidget(self.cbsewagePlant)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.fBaseSetup)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbV = QtWidgets.QCheckBox(self.groupBox)
        self.cbV.setEnabled(True)
        self.cbV.setChecked(False)
        self.cbV.setObjectName("cbV")
        self.verticalLayout_2.addWidget(self.cbV)
        self.cbWaterStation = QtWidgets.QCheckBox(self.groupBox)
        self.cbWaterStation.setObjectName("cbWaterStation")
        self.verticalLayout_2.addWidget(self.cbWaterStation)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.fBaseSetup)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbSK = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbSK.setCheckable(True)
        self.cbSK.setObjectName("cbSK")
        self.verticalLayout_4.addWidget(self.cbSK)
        self.cbD = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbD.setChecked(False)
        self.cbD.setObjectName("cbD")
        self.verticalLayout_4.addWidget(self.cbD)
        self.cbRainPump = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbRainPump.setObjectName("cbRainPump")
        self.verticalLayout_4.addWidget(self.cbRainPump)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_9.addWidget(self.fBaseSetup)
        self.frame_2 = QtWidgets.QFrame(self.fMainTools)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight)
        self.frame_14 = QtWidgets.QFrame(self.fMainTools)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(530, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.Round_or_Square = QtWidgets.QCheckBox(self.frame_14)
        self.Round_or_Square.setChecked(True)
        self.Round_or_Square.setObjectName("Round_or_Square")
        self.horizontalLayout_6.addWidget(self.Round_or_Square)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.fMainTools)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbAddRoad = QtWidgets.QPushButton(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbAddRoad.setFont(font)
        self.pbAddRoad.setObjectName("pbAddRoad")
        self.horizontalLayout_4.addWidget(self.pbAddRoad)
        self.pbKoostaServituut = QtWidgets.QPushButton(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pbKoostaServituut.setFont(font)
        self.pbKoostaServituut.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons_a/cloud-lightning.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbKoostaServituut.setIcon(icon2)
        self.pbKoostaServituut.setIconSize(QtCore.QSize(25, 25))
        self.pbKoostaServituut.setObjectName("pbKoostaServituut")
        self.horizontalLayout_4.addWidget(self.pbKoostaServituut, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.groupBox_7 = QtWidgets.QGroupBox(self.fMainTools)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_17.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lblLayoutName = QtWidgets.QLineEdit(self.groupBox_8)
        self.lblLayoutName.setStyleSheet("")
        self.lblLayoutName.setObjectName("lblLayoutName")
        self.verticalLayout_16.addWidget(self.lblLayoutName)
        self.horizontalLayout_17.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lblMapObject = QtWidgets.QLineEdit(self.groupBox_9)
        self.lblMapObject.setStyleSheet("")
        self.lblMapObject.setObjectName("lblMapObject")
        self.verticalLayout_17.addWidget(self.lblMapObject)
        self.horizontalLayout_17.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.cmbScale = QtWidgets.QComboBox(self.groupBox_10)
        self.cmbScale.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbScale.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbScale.setObjectName("cmbScale")
        self.verticalLayout_18.addWidget(self.cmbScale)
        self.horizontalLayout_17.addWidget(self.groupBox_10)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.frame_11 = QtWidgets.QFrame(self.fMainTools)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.pbprint = QtWidgets.QPushButton(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbprint.setFont(font)
        self.pbprint.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../../icons/Icons_hele/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbprint.setIcon(icon3)
        self.pbprint.setObjectName("pbprint")
        self.horizontalLayout_18.addWidget(self.pbprint)
        self.verticalLayout_9.addWidget(self.frame_11)
        self.frame_4 = QtWidgets.QFrame(self.fMainTools)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_9.addWidget(self.frame_4)
        self.ActionTools = QtWidgets.QFrame(self.fMainTools)
        self.ActionTools.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ActionTools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ActionTools.setObjectName("ActionTools")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ActionTools)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9.addWidget(self.ActionTools)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.fButtons = QtWidgets.QFrame(self.fMainTools)
        self.fButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fButtons.setObjectName("fButtons")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.fButtons)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(411, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.pbCancel = QtWidgets.QPushButton(self.fButtons)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../icons/Icons_hele/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbCancel.setIcon(icon4)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_7.addWidget(self.pbCancel)
        self.pbSave = QtWidgets.QPushButton(self.fButtons)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pbSave.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../icons/Icons_hele/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSave.setIcon(icon5)
        self.pbSave.setIconSize(QtCore.QSize(16, 16))
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_7.addWidget(self.pbSave)
        self.verticalLayout_9.addWidget(self.fButtons)
        self.horizontalLayout.addWidget(self.fMainTools)
        self.fHelpMenu = QtWidgets.QFrame(self.fMain)
        self.fHelpMenu.setMinimumSize(QtCore.QSize(200, 0))
        self.fHelpMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fHelpMenu.setStyleSheet("")
        self.fHelpMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fHelpMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fHelpMenu.setObjectName("fHelpMenu")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.fHelpMenu)
        self.verticalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.fHelpMenu)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.fHelpMenu)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_10.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.fHelpMenu)
        self.verticalLayout_6.addWidget(self.fMain)

        self.retranslateUi(servituutDialogBase)
        QtCore.QMetaObject.connectSlotsByName(servituutDialogBase)

    def retranslateUi(self, servituutDialogBase):
        _translate = QtCore.QCoreApplication.translate
        servituutDialogBase.setWindowTitle(_translate("servituutDialogBase", "servituut"))
        self.leInfo.setText(_translate("servituutDialogBase", "Ala koostatakse kandele:"))
        self.lSelectedEasment.setText(_translate("servituutDialogBase", "Servituudi nimi"))
        self.leSelectedProperties.setText(_translate("servituutDialogBase", "Kinnistud"))
        self.pbValiKinnistu.setText(_translate("servituutDialogBase", "Vali kinnistu"))
        self.label.setText(_translate("servituutDialogBase", "Puhver: 0"))
        self.pbClearCadastrals.setText(_translate("servituutDialogBase", "Tühista"))
        self.groupBox_2.setTitle(_translate("servituutDialogBase", "K (muuda diameeter/sügavus)"))
        self.lineEdit_3.setText(_translate("servituutDialogBase", "Di"))
        self.lblDeK.setText(_translate("servituutDialogBase", "160"))
        self.lineEdit_11.setText(_translate("servituutDialogBase", "mm"))
        self.lineEdit_5.setText(_translate("servituutDialogBase", "H"))
        self.lblHK.setText(_translate("servituutDialogBase", "1,98"))
        self.lineEdit_8.setText(_translate("servituutDialogBase", "m"))
        self.groupBox_5.setTitle(_translate("servituutDialogBase", "V (muuda diameeter/sügavus)"))
        self.lineEdit_2.setText(_translate("servituutDialogBase", "Di"))
        self.lblDeV.setText(_translate("servituutDialogBase", "110"))
        self.lineEdit.setText(_translate("servituutDialogBase", "mm"))
        self.lineEdit_7.setText(_translate("servituutDialogBase", "H"))
        self.lblHV.setText(_translate("servituutDialogBase", "1,65"))
        self.lineEdit_10.setText(_translate("servituutDialogBase", "m"))
        self.groupBox_6.setTitle(_translate("servituutDialogBase", "SK (muuda diameeter/sügavus)"))
        self.lineEdit_4.setText(_translate("servituutDialogBase", "Di"))
        self.lblDeSK.setText(_translate("servituutDialogBase", "250"))
        self.lineEdit_12.setText(_translate("servituutDialogBase", "mm"))
        self.lineEdit_6.setText(_translate("servituutDialogBase", "H"))
        self.lblHSK.setText(_translate("servituutDialogBase", "1,9"))
        self.lineEdit_9.setText(_translate("servituutDialogBase", "m"))
        self.groupBox_4.setTitle(_translate("servituutDialogBase", "Reveevõrk"))
        self.cbK.setText(_translate("servituutDialogBase", "Torud"))
        self.cbKSK.setText(_translate("servituutDialogBase", "Survetorud"))
        self.cbsewagePupming.setText(_translate("servituutDialogBase", "Pumpla"))
        self.cbSewageDump.setText(_translate("servituutDialogBase", "Purgimissõlm"))
        self.cbsewagePlant.setText(_translate("servituutDialogBase", "Reoveepuhasti"))
        self.groupBox.setTitle(_translate("servituutDialogBase", "Veevõrk"))
        self.cbV.setText(_translate("servituutDialogBase", "Torud"))
        self.cbWaterStation.setText(_translate("servituutDialogBase", "Jaam"))
        self.groupBox_3.setTitle(_translate("servituutDialogBase", "Sademevee võrk"))
        self.cbSK.setText(_translate("servituutDialogBase", "Torud"))
        self.cbD.setText(_translate("servituutDialogBase", "Drenaaž"))
        self.cbRainPump.setText(_translate("servituutDialogBase", "Pumpla"))
        self.Round_or_Square.setText(_translate("servituutDialogBase", "puhver kuju ümar"))
        self.pbAddRoad.setText(_translate("servituutDialogBase", "Koosta tee ala servituut"))
        self.pbKoostaServituut.setText(_translate("servituutDialogBase", "Koosta skeem"))
        self.groupBox_7.setTitle(_translate("servituutDialogBase", "Trükkimislehe seadistused"))
        self.groupBox_8.setTitle(_translate("servituutDialogBase", "Trüki lehe nimetus"))
        self.lblLayoutName.setText(_translate("servituutDialogBase", "Kitsendus"))
        self.groupBox_9.setTitle(_translate("servituutDialogBase", "Kaardi kuva ala nimetus"))
        self.lblMapObject.setText(_translate("servituutDialogBase", "Map 1"))
        self.groupBox_10.setTitle(_translate("servituutDialogBase", "Mõõtkava"))
        self.pbprint.setText(_translate("servituutDialogBase", "Eelvaade*"))
        self.pbCancel.setText(_translate("servituutDialogBase", "Tühista"))
        self.pbSave.setText(_translate("servituutDialogBase", "Salvesta"))
        self.label_4.setText(_translate("servituutDialogBase", "Kuidas tööriista\n"
"kasutada?"))
        self.textEdit.setHtml(_translate("servituutDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">NB! Tärniga väärtused on arendamisel!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Servituudi nimi </span>- näed, millisele servituudile skeemi koostama hakkad </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Vali kinnistu</span> - aktiveerib kinnistute aluskihi ning võimaldab valida kinnistuid.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">   1. Vali konkreetne kinnistu, vajutades hiirega sobival kinnistul. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">   2. </span>Mitme kinnistu valimiseks hoia all Ctrl klahvi.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">   3. Hoides all Ctrl klahvi,  saad kinnistuid valikust lisada või eemaldada.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> <span style=\" font-weight:600;\">Kinnistud </span>-<span style=\" font-weight:600;\"> </span> kastis kuvatakse valitud kinnistud.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Tühista </span>- tühistab varasema kinnistute valiku.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Eelvaade</span><br />1. Testimiseks seadista: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aaaaff;\"> </span><span style=\" font-weight:600; font-style:italic; color:#aaaaff;\"> QGIS&gt;Seaded&gt;Suvandid&gt;Layouts</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Lisa aadress, kus asub sinu:QGIS: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#5500ff;\"> </span><span style=\" font-weight:600; font-style:italic; color:#aaaaff;\"> C:/Users/&quot;Kasutaja&quot;/Desktop/Plugins/mailabl-qgis/mailabl-qgis/QGIS_styles/Layouts</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Koosta uus Layout: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aaaaff;\">  </span><span style=\" font-weight:600; font-style:italic; color:#aaaaff;\">Projekt&gt;Layout&gt;Manager&gt;Uus Mallist</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. Vali rippmenüüst &quot;MailablEasementLayoutTemp&quot; ja vajuta nuppu <span style=\" font-weight:600;\">&quot;Koosta&quot;</span> või <span style=\" font-weight:600;\">&quot;Greate&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5.<span style=\" font-weight:600;\"> </span>Koosta uue nimega mall (Testimiseks nimeta see &quot;<span style=\" font-weight:600;\">Kitsendus</span>&quot;)<br /><br /></p></body></html>"))
