# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kalver\Desktop\Plugins\mailabl-qgis\mailabl-qgis\Functions\Easements\widgets\Servituut.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_servituutDialogBase(object):
    def setupUi(self, servituutDialogBase):
        servituutDialogBase.setObjectName("servituutDialogBase")
        servituutDialogBase.resize(900, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(servituutDialogBase.sizePolicy().hasHeightForWidth())
        servituutDialogBase.setSizePolicy(sizePolicy)
        servituutDialogBase.setMinimumSize(QtCore.QSize(900, 750))
        servituutDialogBase.setMaximumSize(QtCore.QSize(900, 750))
        servituutDialogBase.setStyleSheet("\n"
"#lblDialer{\n"
"    background-color: None;\n"
"    backround: None;\n"
"    border: None\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"#leInfo,#leSelectedProperties {\n"
"    border: None;\n"
"    background-color: #272c35;\n"
"    color: #c5c5d2;\n"
"    padding-left: 10px; /* Adjust the left padding as needed */\n"
"    padding-right: 0px; /* Adjust the right padding as needed */\n"
"    padding-top: 0px; /* Adjust the top padding as needed */\n"
"    padding-bottom: 0px; /* Adjust the bottom padding as needed */\n"
"}\n"
"\n"
"\n"
"#fHeader, #fHelpMenu, \n"
"#fSettingsFolders, #fSettingsFolderStucture,\n"
"#fSettingsMain \n"
"{\n"
"   border: 2px solid #4d4d5b;    /*Same border style as QLineEdit */\n"
"    border-radius: 5px;\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"\n"
"QWidget{\n"
"    background-color: #272c35;\n"
"    color:#c5c5d2\n"
"}\n"
"\n"
"\n"
"/*esialgu jaotamata omadused*/\n"
"QComboBox {\n"
"    background-color: #40414f; /* Set the background color */\n"
"    color: #ececf1;\n"
"    border: 1px solid #565869;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"/* Style the dropdown area */\n"
"QComboBox::drop-down {\n"
"    background-color: #40414f;\n"
"    border: 0px solid #40414f;\n"
"    border-radius: 10px;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: left; /* Center the arrow icon */\n"
"}\n"
"\n"
"/* Style the arrow inside the dropdown */\n"
"QComboBox::down-arrow {\n"
"\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 6px solid #40414f;\n"
"    border-right: 6px solid #40414f;\n"
"    border-top: 8px solid #ececf1; /* Adjust the color to match your design */\n"
"    margin: 8px auto; /* Center the arrow */\n"
"}\n"
"\n"
"QComboBox::on {\n"
"    border: 0.5px solid #acacbe;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"   background-color: #3d3e47;\n"
" /* Set the background color for the disabled state */\n"
"    border: 1px solid #565869; /* Adjust border color for disabled state */\n"
"    color: #8a95a5; /* Adjust text color for disabled state */\n"
"}\n"
"\n"
"\n"
"QCheckBox:disabled {\n"
"    color: #8a95a5; /* Adjust text color for disabled state */\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QAbstractItemView {\n"
"    background-color:#40414f;\n"
"    color:#ececf1;\n"
"    border: 1px solid #565869;\n"
"    border-radius: 4px;\n"
"    padding-left: 5px\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    padding: 2px 8px;\n"
"    text-align: center;\n"
"    border-radius: 6px;\n"
"    background-color:#40414f;\n"
"    border: 1px solid #565869;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8e8ea0;\n"
"    border: 0.5px solid #acacbe;\n"
"    color: #343541;\n"
"    text-align: center;    \n"
"    padding: 2px 8px;\n"
"    border-radius: 6px;    \n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #303040; /* Adjusted disabled background color */\n"
"    border: 1px solid #707070; /* Adjust border color for disabled state */\n"
"    color: #8a95a5; /* Adjust text color for disabled state */\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: #40414f;\n"
"    color: #ececf1;\n"
"    border: 1px solid #565869;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"#label_12,\n"
"#label_11\n"
" {\n"
"    background-color: #40414f;\n"
"    color: #ececf1;\n"
"    border: 1px solid #565869;\n"
"\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #35363f;  /* Lighter background color */\n"
"    color: #ececf1;\n"
"    /*border: 1px solid #4d4d5b;  Thinner border with a different color */\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #3d3e47;  /* Slightly darker background color on hover */\n"
"}\n"
"\n"
"/* Remove top and side borders */\n"
"QLineEdit {\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color: #8a95a5; /* Adjust text color for disabled state */\n"
"}\n"
"\n"
"\n"
"")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(servituutDialogBase)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fMain = QtWidgets.QFrame(servituutDialogBase)
        self.fMain.setMinimumSize(QtCore.QSize(0, 200))
        self.fMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fMain.setObjectName("fMain")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fMain)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fMainTools = QtWidgets.QFrame(self.fMain)
        self.fMainTools.setStyleSheet("")
        self.fMainTools.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fMainTools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fMainTools.setObjectName("fMainTools")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.fMainTools)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.fSelectedItem = QtWidgets.QFrame(self.fMainTools)
        self.fSelectedItem.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fSelectedItem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fSelectedItem.setObjectName("fSelectedItem")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fSelectedItem)
        self.horizontalLayout_3.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fItemSelections = QtWidgets.QFrame(self.fSelectedItem)
        self.fItemSelections.setMinimumSize(QtCore.QSize(0, 100))
        self.fItemSelections.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fItemSelections.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fItemSelections.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fItemSelections.setObjectName("fItemSelections")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fItemSelections)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3.addWidget(self.fItemSelections)
        self.frame_3 = QtWidgets.QFrame(self.fSelectedItem)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 180))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_11.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.leInfo = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.leInfo.setFont(font)
        self.leInfo.setReadOnly(True)
        self.leInfo.setObjectName("leInfo")
        self.verticalLayout_11.addWidget(self.leInfo)
        self.lSelectedEasment = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lSelectedEasment.setFont(font)
        self.lSelectedEasment.setObjectName("lSelectedEasment")
        self.verticalLayout_11.addWidget(self.lSelectedEasment)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.leSelectedProperties = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.leSelectedProperties.setFont(font)
        self.leSelectedProperties.setReadOnly(True)
        self.leSelectedProperties.setObjectName("leSelectedProperties")
        self.verticalLayout_5.addWidget(self.leSelectedProperties)
        self.tvProperties = QtWidgets.QTableView(self.frame)
        self.tvProperties.setObjectName("tvProperties")
        self.verticalLayout_5.addWidget(self.tvProperties)
        self.verticalLayout_11.addWidget(self.frame)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(self.fSelectedItem)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout.setContentsMargins(0, 18, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbValiKinnistu = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbValiKinnistu.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../../icons/iconoir--map-pin-plus_asukoht.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbValiKinnistu.setIcon(icon)
        self.pbValiKinnistu.setIconSize(QtCore.QSize(18, 18))
        self.pbValiKinnistu.setObjectName("pbValiKinnistu")
        self.verticalLayout.addWidget(self.pbValiKinnistu)
        self.label = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dPuhvriSuurus = QtWidgets.QDial(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dPuhvriSuurus.sizePolicy().hasHeightForWidth())
        self.dPuhvriSuurus.setSizePolicy(sizePolicy)
        self.dPuhvriSuurus.setObjectName("dPuhvriSuurus")
        self.verticalLayout.addWidget(self.dPuhvriSuurus)
        self.pbClearCadastrals = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbClearCadastrals.setFont(font)
        self.pbClearCadastrals.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../../icons/Icons_hele/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClearCadastrals.setIcon(icon1)
        self.pbClearCadastrals.setIconSize(QtCore.QSize(16, 16))
        self.pbClearCadastrals.setObjectName("pbClearCadastrals")
        self.verticalLayout.addWidget(self.pbClearCadastrals)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_9.addWidget(self.fSelectedItem, 0, QtCore.Qt.AlignTop)
        self.TestValues = QtWidgets.QFrame(self.fMainTools)
        self.TestValues.setMinimumSize(QtCore.QSize(0, 100))
        self.TestValues.setMaximumSize(QtCore.QSize(16777215, 100))
        self.TestValues.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TestValues.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TestValues.setObjectName("TestValues")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TestValues)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.TestValues)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_15.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_12 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_10.addWidget(self.lineEdit_3)
        self.lblDeK = QtWidgets.QLineEdit(self.frame_12)
        self.lblDeK.setMinimumSize(QtCore.QSize(60, 0))
        self.lblDeK.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblDeK.setObjectName("lblDeK")
        self.horizontalLayout_10.addWidget(self.lblDeK)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_11.setFrame(True)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_10.addWidget(self.lineEdit_11)
        self.verticalLayout_15.addWidget(self.frame_12)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_15.addWidget(self.lineEdit_5)
        self.lblHK = QtWidgets.QLineEdit(self.frame_5)
        self.lblHK.setMinimumSize(QtCore.QSize(90, 0))
        self.lblHK.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblHK.setObjectName("lblHK")
        self.horizontalLayout_15.addWidget(self.lblHK)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_8.setFrame(True)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_15.addWidget(self.lineEdit_8)
        self.verticalLayout_15.addWidget(self.frame_5)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.TestValues)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_11.addWidget(self.lineEdit_2)
        self.lblDeV = QtWidgets.QLineEdit(self.frame_7)
        self.lblDeV.setMinimumSize(QtCore.QSize(90, 0))
        self.lblDeV.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblDeV.setObjectName("lblDeV")
        self.horizontalLayout_11.addWidget(self.lblDeV)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_7.setFrame(True)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_12.addWidget(self.lineEdit_7)
        self.lblHV = QtWidgets.QLineEdit(self.frame_8)
        self.lblHV.setMinimumSize(QtCore.QSize(90, 0))
        self.lblHV.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblHV.setObjectName("lblHV")
        self.horizontalLayout_12.addWidget(self.lblHV)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_10.setFrame(True)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_12.addWidget(self.lineEdit_10)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.horizontalLayout_9.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.TestValues)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_14.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_9 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_4.setFrame(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_13.addWidget(self.lineEdit_4)
        self.lblDeSK = QtWidgets.QLineEdit(self.frame_9)
        self.lblDeSK.setMinimumSize(QtCore.QSize(90, 0))
        self.lblDeSK.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblDeSK.setObjectName("lblDeSK")
        self.horizontalLayout_13.addWidget(self.lblDeSK)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_12.setFrame(True)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_13.addWidget(self.lineEdit_12)
        self.verticalLayout_14.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_6.setFrame(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_14.addWidget(self.lineEdit_6)
        self.lblHSK = QtWidgets.QLineEdit(self.frame_10)
        self.lblHSK.setMinimumSize(QtCore.QSize(90, 0))
        self.lblHSK.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblHSK.setObjectName("lblHSK")
        self.horizontalLayout_14.addWidget(self.lblHSK)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_9.setFrame(True)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_14.addWidget(self.lineEdit_9)
        self.verticalLayout_14.addWidget(self.frame_10)
        self.horizontalLayout_9.addWidget(self.groupBox_6)
        self.verticalLayout_9.addWidget(self.TestValues)
        self.fBaseSetup = QtWidgets.QFrame(self.fMainTools)
        self.fBaseSetup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fBaseSetup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fBaseSetup.setObjectName("fBaseSetup")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fBaseSetup)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.fBaseSetup)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cbK = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbK.setChecked(False)
        self.cbK.setObjectName("cbK")
        self.verticalLayout_8.addWidget(self.cbK)
        self.cbKSK = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbKSK.setCheckable(True)
        self.cbKSK.setChecked(False)
        self.cbKSK.setObjectName("cbKSK")
        self.verticalLayout_8.addWidget(self.cbKSK)
        self.cbsewagePupming = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbsewagePupming.setCheckable(True)
        self.cbsewagePupming.setObjectName("cbsewagePupming")
        self.verticalLayout_8.addWidget(self.cbsewagePupming)
        self.cbSewageDump = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbSewageDump.setCheckable(True)
        self.cbSewageDump.setObjectName("cbSewageDump")
        self.verticalLayout_8.addWidget(self.cbSewageDump)
        self.cbsewagePlant = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbsewagePlant.setCheckable(True)
        self.cbsewagePlant.setObjectName("cbsewagePlant")
        self.verticalLayout_8.addWidget(self.cbsewagePlant)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.fBaseSetup)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbV = QtWidgets.QCheckBox(self.groupBox)
        self.cbV.setChecked(False)
        self.cbV.setObjectName("cbV")
        self.verticalLayout_2.addWidget(self.cbV)
        self.cbWaterStation = QtWidgets.QCheckBox(self.groupBox)
        self.cbWaterStation.setObjectName("cbWaterStation")
        self.verticalLayout_2.addWidget(self.cbWaterStation)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.fBaseSetup)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbSK = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbSK.setCheckable(True)
        self.cbSK.setObjectName("cbSK")
        self.verticalLayout_4.addWidget(self.cbSK)
        self.cbD = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbD.setChecked(False)
        self.cbD.setObjectName("cbD")
        self.verticalLayout_4.addWidget(self.cbD)
        self.cbRainPump = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbRainPump.setObjectName("cbRainPump")
        self.verticalLayout_4.addWidget(self.cbRainPump)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_9.addWidget(self.fBaseSetup)
        self.frame_2 = QtWidgets.QFrame(self.fMainTools)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight)
        self.frame_14 = QtWidgets.QFrame(self.fMainTools)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(530, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.Round_or_Square = QtWidgets.QCheckBox(self.frame_14)
        self.Round_or_Square.setChecked(True)
        self.Round_or_Square.setObjectName("Round_or_Square")
        self.horizontalLayout_6.addWidget(self.Round_or_Square)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.fMainTools)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbAddRoad = QtWidgets.QPushButton(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbAddRoad.setFont(font)
        self.pbAddRoad.setObjectName("pbAddRoad")
        self.horizontalLayout_4.addWidget(self.pbAddRoad)
        self.pbKoostaServituut = QtWidgets.QPushButton(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pbKoostaServituut.setFont(font)
        self.pbKoostaServituut.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons_a/cloud-lightning.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbKoostaServituut.setIcon(icon2)
        self.pbKoostaServituut.setIconSize(QtCore.QSize(25, 25))
        self.pbKoostaServituut.setObjectName("pbKoostaServituut")
        self.horizontalLayout_4.addWidget(self.pbKoostaServituut, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.groupBox_7 = QtWidgets.QGroupBox(self.fMainTools)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_17.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lblLayoutName = QtWidgets.QLineEdit(self.groupBox_8)
        self.lblLayoutName.setStyleSheet("")
        self.lblLayoutName.setObjectName("lblLayoutName")
        self.verticalLayout_16.addWidget(self.lblLayoutName)
        self.horizontalLayout_17.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lblMapObject = QtWidgets.QLineEdit(self.groupBox_9)
        self.lblMapObject.setStyleSheet("")
        self.lblMapObject.setObjectName("lblMapObject")
        self.verticalLayout_17.addWidget(self.lblMapObject)
        self.horizontalLayout_17.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.cmbScale = QtWidgets.QComboBox(self.groupBox_10)
        self.cmbScale.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbScale.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbScale.setObjectName("cmbScale")
        self.verticalLayout_18.addWidget(self.cmbScale)
        self.horizontalLayout_17.addWidget(self.groupBox_10)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.frame_11 = QtWidgets.QFrame(self.fMainTools)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.pbprint = QtWidgets.QPushButton(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbprint.setFont(font)
        self.pbprint.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../../icons/Icons_hele/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbprint.setIcon(icon3)
        self.pbprint.setObjectName("pbprint")
        self.horizontalLayout_18.addWidget(self.pbprint)
        self.verticalLayout_9.addWidget(self.frame_11)
        self.frame_4 = QtWidgets.QFrame(self.fMainTools)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_9.addWidget(self.frame_4)
        self.ActionTools = QtWidgets.QFrame(self.fMainTools)
        self.ActionTools.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ActionTools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ActionTools.setObjectName("ActionTools")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ActionTools)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9.addWidget(self.ActionTools)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.fButtons = QtWidgets.QFrame(self.fMainTools)
        self.fButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fButtons.setObjectName("fButtons")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.fButtons)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(411, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.pbCancel = QtWidgets.QPushButton(self.fButtons)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../icons/Icons_hele/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbCancel.setIcon(icon4)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_7.addWidget(self.pbCancel)
        self.pbSave = QtWidgets.QPushButton(self.fButtons)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pbSave.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\Functions\\Easements\\widgets\\../../icons/Icons_hele/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSave.setIcon(icon5)
        self.pbSave.setIconSize(QtCore.QSize(16, 16))
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_7.addWidget(self.pbSave)
        self.verticalLayout_9.addWidget(self.fButtons)
        self.horizontalLayout.addWidget(self.fMainTools)
        self.fHelpMenu = QtWidgets.QFrame(self.fMain)
        self.fHelpMenu.setMinimumSize(QtCore.QSize(200, 0))
        self.fHelpMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fHelpMenu.setStyleSheet("")
        self.fHelpMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fHelpMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fHelpMenu.setObjectName("fHelpMenu")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.fHelpMenu)
        self.verticalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.fHelpMenu)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.fHelpMenu)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_10.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.fHelpMenu)
        self.verticalLayout_6.addWidget(self.fMain)

        self.retranslateUi(servituutDialogBase)
        QtCore.QMetaObject.connectSlotsByName(servituutDialogBase)

    def retranslateUi(self, servituutDialogBase):
        _translate = QtCore.QCoreApplication.translate
        servituutDialogBase.setWindowTitle(_translate("servituutDialogBase", "servituut"))
        self.leInfo.setText(_translate("servituutDialogBase", "Ala koostatakse kandele:"))
        self.lSelectedEasment.setText(_translate("servituutDialogBase", "Servituudi nimi"))
        self.leSelectedProperties.setText(_translate("servituutDialogBase", "Kinnistud"))
        self.pbValiKinnistu.setText(_translate("servituutDialogBase", "Vali kinnistu"))
        self.label.setText(_translate("servituutDialogBase", "Puhver: 0"))
        self.pbClearCadastrals.setText(_translate("servituutDialogBase", "Tühista"))
        self.groupBox_2.setTitle(_translate("servituutDialogBase", "K (muuda diameeter/sügavus)"))
        self.lineEdit_3.setText(_translate("servituutDialogBase", "Di"))
        self.lblDeK.setText(_translate("servituutDialogBase", "160"))
        self.lineEdit_11.setText(_translate("servituutDialogBase", "mm"))
        self.lineEdit_5.setText(_translate("servituutDialogBase", "H"))
        self.lblHK.setText(_translate("servituutDialogBase", "1,98"))
        self.lineEdit_8.setText(_translate("servituutDialogBase", "m"))
        self.groupBox_5.setTitle(_translate("servituutDialogBase", "V (muuda diameeter/sügavus)"))
        self.lineEdit_2.setText(_translate("servituutDialogBase", "Di"))
        self.lblDeV.setText(_translate("servituutDialogBase", "110"))
        self.lineEdit.setText(_translate("servituutDialogBase", "mm"))
        self.lineEdit_7.setText(_translate("servituutDialogBase", "H"))
        self.lblHV.setText(_translate("servituutDialogBase", "1,65"))
        self.lineEdit_10.setText(_translate("servituutDialogBase", "m"))
        self.groupBox_6.setTitle(_translate("servituutDialogBase", "SK (muuda diameeter/sügavus)"))
        self.lineEdit_4.setText(_translate("servituutDialogBase", "Di"))
        self.lblDeSK.setText(_translate("servituutDialogBase", "250"))
        self.lineEdit_12.setText(_translate("servituutDialogBase", "mm"))
        self.lineEdit_6.setText(_translate("servituutDialogBase", "H"))
        self.lblHSK.setText(_translate("servituutDialogBase", "1,9"))
        self.lineEdit_9.setText(_translate("servituutDialogBase", "m"))
        self.groupBox_4.setTitle(_translate("servituutDialogBase", "Reveevõrk"))
        self.cbK.setText(_translate("servituutDialogBase", "Torud"))
        self.cbKSK.setText(_translate("servituutDialogBase", "Survetorud"))
        self.cbsewagePupming.setText(_translate("servituutDialogBase", "Pumpla"))
        self.cbSewageDump.setText(_translate("servituutDialogBase", "Purgimissõlm"))
        self.cbsewagePlant.setText(_translate("servituutDialogBase", "Reoveepuhasti"))
        self.groupBox.setTitle(_translate("servituutDialogBase", "Veevõrk"))
        self.cbV.setText(_translate("servituutDialogBase", "Torud"))
        self.cbWaterStation.setText(_translate("servituutDialogBase", "Jaam"))
        self.groupBox_3.setTitle(_translate("servituutDialogBase", "Sademevee võrk"))
        self.cbSK.setText(_translate("servituutDialogBase", "Torud"))
        self.cbD.setText(_translate("servituutDialogBase", "Drenaaž"))
        self.cbRainPump.setText(_translate("servituutDialogBase", "Pumpla"))
        self.Round_or_Square.setText(_translate("servituutDialogBase", "puhver kuju ümar"))
        self.pbAddRoad.setText(_translate("servituutDialogBase", "Koosta tee ala servituut"))
        self.pbKoostaServituut.setText(_translate("servituutDialogBase", "Koosta skeem"))
        self.groupBox_7.setTitle(_translate("servituutDialogBase", "Trükkimislehe seadistused"))
        self.groupBox_8.setTitle(_translate("servituutDialogBase", "Trüki lehe nimetus"))
        self.lblLayoutName.setText(_translate("servituutDialogBase", "Kitsendus"))
        self.groupBox_9.setTitle(_translate("servituutDialogBase", "Kaardi kuva ala nimetus"))
        self.lblMapObject.setText(_translate("servituutDialogBase", "Map 1"))
        self.groupBox_10.setTitle(_translate("servituutDialogBase", "Mõõtkava"))
        self.pbprint.setText(_translate("servituutDialogBase", "Eelvaade*"))
        self.pbCancel.setText(_translate("servituutDialogBase", "Tühista"))
        self.pbSave.setText(_translate("servituutDialogBase", "Salvesta"))
        self.label_4.setText(_translate("servituutDialogBase", "Kuidas tööriista\n"
"kasutada?"))
        self.textEdit.setHtml(_translate("servituutDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">NB! Tärniga väärtused on arendamisel!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Servituudi nimi </span>- näed, millisele servituudile skeemi koostama hakkad </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Vali kinnistu</span> - aktiveerib kinnistute aluskihi ning võimaldab valida kinnistuid.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">   1. Vali konkreetne kinnistu, vajutades hiirega sobival kinnistul. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">   2. </span>Mitme kinnistu valimiseks hoia all Ctrl klahvi.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">   3. Hoides all Ctrl klahvi,  saad kinnistuid valikust lisada või eemaldada.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> <span style=\" font-weight:600;\">Kinnistud </span>-<span style=\" font-weight:600;\"> </span> kastis kuvatakse valitud kinnistud.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Tühista </span>- tühistab varasema kinnistute valiku.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Eelvaade</span><br />1. Testimiseks seadista: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aaaaff;\"> </span><span style=\" font-weight:600; font-style:italic; color:#aaaaff;\"> QGIS&gt;Seaded&gt;Suvandid&gt;Layouts</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Lisa aadress, kus asub sinu:QGIS: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#5500ff;\"> </span><span style=\" font-weight:600; font-style:italic; color:#aaaaff;\"> C:/Users/&quot;Kasutaja&quot;/Desktop/Plugins/mailabl-qgis/mailabl-qgis/QGIS_styles/Layouts</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Koosta uus Layout: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aaaaff;\">  </span><span style=\" font-weight:600; font-style:italic; color:#aaaaff;\">Projekt&gt;Layout&gt;Manager&gt;Uus Mallist</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. Vali rippmenüüst &quot;MailablEasementLayoutTemp&quot; ja vajuta nuppu <span style=\" font-weight:600;\">&quot;Koosta&quot;</span> või <span style=\" font-weight:600;\">&quot;Greate&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5.<span style=\" font-weight:600;\"> </span>Koosta uue nimega mall (Testimiseks nimeta see &quot;<span style=\" font-weight:600;\">Kitsendus</span>&quot;)<br /><br /></p></body></html>"))
