# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kalver\Desktop\Plugins\mailabl-qgis\mailabl-qgis\config\confWidgets\ContractsSetup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayeAdjuster(object):
    def setupUi(self, LayeAdjuster):
        LayeAdjuster.setObjectName("LayeAdjuster")
        LayeAdjuster.resize(690, 226)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LayeAdjuster.sizePolicy().hasHeightForWidth())
        LayeAdjuster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        LayeAdjuster.setFont(font)
        LayeAdjuster.setStyleSheet("/*üleüldine taust ja toonid*/\n"
"/*--gray-0: #fff;\n"
"    --gray-50: #f7f7f8;\n"
"    --gray-100: #ececf1;\n"
"    --gray-200: #d9d9e3;\n"
"    --gray-300: #c5c5d2;\n"
"    --gray-400: #acacbe;\n"
"    --gray-500: #8e8ea0;\n"
"    --gray-600: #565869;\n"
"    --gray-700: #40414f;\n"
"    --gray-800: #343541;\n"
"    --gray-900: #202123;\n"
"    --gray-950: #050509;\n"
"*/\n"
"\n"
"/*style the combobox itself*/\n"
"\n"
"\n"
"QWidget{\n"
"    background-color: #272c35;\n"
"    color:#c5c5d2\n"
"}\n"
"\n"
"\n"
"/*esialgu jaotamata omadused*/\n"
"QComboBox{\n"
"\n"
"    background-color:#40414f;\n"
"    color:#ececf1;\n"
"    border: 1px solid #565869;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px\n"
"}\n"
"\n"
"/*Style the dropdown area*/\n"
"QComboBox::drop-down{\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:135, stop:0.704545 rgba(64, 65, 79), stop:1 rgba(217, 217, 227));\n"
"    border: 1px solid #565869;\n"
"    border-radius: 8px;\n"
"    height:16px;\n"
"    width: 16px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: left\n"
"}\n"
"\n"
"QComboBox::on{\n"
"\n"
"      border: 0.5px solid #acacbe;\n"
"}\n"
"\n"
"QAbstractItemView {\n"
"    background-color:#40414f;\n"
"    color:#ececf1;\n"
"    border: 1px solid #565869;\n"
"    border-radius: 4px;\n"
"    padding-left: 5px\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    padding: 2px 8px;\n"
"    text-align: center;\n"
"    border-radius: 6px;\n"
"    background-color:#40414f;\n"
"    border: 1px solid #565869;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8e8ea0;\n"
"    border: 0.5px solid #acacbe;\n"
"    color: #343541;\n"
"    text-align: center;    \n"
"    padding: 2px 8px;\n"
"    border-radius: 6px;\n"
"    \n"
"}\n"
"\n"
"QLabel {\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LayeAdjuster)
        self.verticalLayout.setObjectName("verticalLayout")
        self.f_Main = QtWidgets.QFrame(LayeAdjuster)
        self.f_Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Main.setObjectName("f_Main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.f_Main)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.f_Main_2 = QtWidgets.QFrame(self.f_Main)
        self.f_Main_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Main_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Main_2.setObjectName("f_Main_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.f_Main_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.f_Main_3 = QtWidgets.QFrame(self.f_Main_2)
        self.f_Main_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Main_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Main_3.setObjectName("f_Main_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.f_Main_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblCurrect_Cadastral_2 = QtWidgets.QLabel(self.f_Main_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lblCurrect_Cadastral_2.setFont(font)
        self.lblCurrect_Cadastral_2.setObjectName("lblCurrect_Cadastral_2")
        self.horizontalLayout_3.addWidget(self.lblCurrect_Cadastral_2)
        self.cmbPreferredContractStatuses = QtWidgets.QComboBox(self.f_Main_3)
        self.cmbPreferredContractStatuses.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmbPreferredContractStatuses.setFont(font)
        self.cmbPreferredContractStatuses.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cmbPreferredContractStatuses.setIconSize(QtCore.QSize(6, 6))
        self.cmbPreferredContractStatuses.setObjectName("cmbPreferredContractStatuses")
        self.cmbPreferredContractStatuses.addItem("")
        self.cmbPreferredContractStatuses.setItemText(0, "")
        self.cmbPreferredContractStatuses.addItem("")
        self.cmbPreferredContractStatuses.setItemText(1, "")
        self.cmbPreferredContractStatuses.addItem("")
        self.cmbPreferredContractStatuses.setItemText(2, "")
        self.cmbPreferredContractStatuses.addItem("")
        self.cmbPreferredContractStatuses.setItemText(3, "")
        self.horizontalLayout_3.addWidget(self.cmbPreferredContractStatuses)
        self.verticalLayout_3.addWidget(self.f_Main_3)
        self.verticalLayout_4.addWidget(self.f_Main_2)
        self.f_Main_1 = QtWidgets.QFrame(self.f_Main)
        self.f_Main_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Main_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Main_1.setObjectName("f_Main_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.f_Main_1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblPreferedContractTypes = QtWidgets.QLabel(self.f_Main_1)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lblPreferedContractTypes.setFont(font)
        self.lblPreferedContractTypes.setObjectName("lblPreferedContractTypes")
        self.horizontalLayout.addWidget(self.lblPreferedContractTypes)
        self.cbcb_PreferredContractTypes = QgsCheckableComboBox(self.f_Main_1)
        self.cbcb_PreferredContractTypes.setObjectName("cbcb_PreferredContractTypes")
        self.horizontalLayout.addWidget(self.cbcb_PreferredContractTypes)
        self.verticalLayout_4.addWidget(self.f_Main_1)
        self.verticalLayout.addWidget(self.f_Main)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.f_Buttons = QtWidgets.QFrame(LayeAdjuster)
        self.f_Buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Buttons.setObjectName("f_Buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.f_Buttons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(411, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pbCancel = QtWidgets.QPushButton(self.f_Buttons)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_2.addWidget(self.pbCancel)
        self.pbSave = QtWidgets.QPushButton(self.f_Buttons)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pbSave.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\config\\confWidgets\\../../icons/Icons_hele/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSave.setIcon(icon)
        self.pbSave.setIconSize(QtCore.QSize(18, 18))
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_2.addWidget(self.pbSave)
        self.verticalLayout.addWidget(self.f_Buttons)

        self.retranslateUi(LayeAdjuster)
        QtCore.QMetaObject.connectSlotsByName(LayeAdjuster)

    def retranslateUi(self, LayeAdjuster):
        _translate = QtCore.QCoreApplication.translate
        LayeAdjuster.setWindowTitle(_translate("LayeAdjuster", "Lepingute seaded"))
        self.lblCurrect_Cadastral_2.setText(_translate("LayeAdjuster", "Eelistatud staatus"))
        self.lblPreferedContractTypes.setText(_translate("LayeAdjuster", "Eelistatud lepingu liigid"))
        self.pbCancel.setText(_translate("LayeAdjuster", "Tühista"))
        self.pbSave.setText(_translate("LayeAdjuster", "Salvesta"))
from qgscheckablecombobox import QgsCheckableComboBox
