# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kalver\Desktop\Plugins\mailabl-qgis\mailabl-qgis\config\confWidgets\ProjectSetup – koopia.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayeAdjuster(object):
    def setupUi(self, LayeAdjuster):
        LayeAdjuster.setObjectName("LayeAdjuster")
        LayeAdjuster.resize(1016, 317)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LayeAdjuster.sizePolicy().hasHeightForWidth())
        LayeAdjuster.setSizePolicy(sizePolicy)
        LayeAdjuster.setStyleSheet("/*üleüldine taust ja toonid*/\n"
"/*--gray-0: #fff;\n"
"    --gray-50: #f7f7f8;\n"
"    --gray-100: #ececf1;\n"
"    --gray-200: #d9d9e3;\n"
"    --gray-300: #c5c5d2;\n"
"    --gray-400: #acacbe;\n"
"    --gray-500: #8e8ea0;\n"
"    --gray-600: #565869;\n"
"    --gray-700: #40414f;\n"
"    --gray-800: #343541;\n"
"    --gray-900: #202123;\n"
"    --gray-950: #050509;\n"
"*/\n"
"\n"
"/*style the combobox itself*/\n"
"\n"
"\n"
"QWidget{\n"
"    background-color: #272c35;\n"
"    color:#c5c5d2\n"
"}\n"
"\n"
"\n"
"/*esialgu jaotamata omadused*/\n"
"QComboBox{\n"
"\n"
"    background-color:#40414f;\n"
"    color:#ececf1;\n"
"    border: 1px solid #565869;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px\n"
"}\n"
"\n"
"/*Style the dropdown area*/\n"
"QComboBox::drop-down{\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:135, stop:0.704545 rgba(64, 65, 79), stop:1 rgba(217, 217, 227));\n"
"    border: 1px solid #565869;\n"
"    border-radius: 8px;\n"
"    height:16px;\n"
"    width: 16px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: left\n"
"}\n"
"\n"
"QComboBox::on{\n"
"\n"
"      border: 0.5px solid #acacbe;\n"
"}\n"
"\n"
"QAbstractItemView {\n"
"    background-color:#40414f;\n"
"    color:#ececf1;\n"
"    border: 1px solid #565869;\n"
"    border-radius: 4px;\n"
"    padding-left: 5px\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    padding: 2px 8px;\n"
"    text-align: center;\n"
"    border-radius: 6px;\n"
"    background-color:#40414f;\n"
"    border: 1px solid #565869;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8e8ea0;\n"
"    border: 0.5px solid #acacbe;\n"
"    color: #343541;\n"
"    text-align: center;    \n"
"    padding: 2px 8px;\n"
"    border-radius: 6px;\n"
"    \n"
"}\n"
"\n"
"QLabel {\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LayeAdjuster)
        self.verticalLayout.setObjectName("verticalLayout")
        self.f_Label = QtWidgets.QFrame(LayeAdjuster)
        self.f_Label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Label.setObjectName("f_Label")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.f_Label)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.f_Label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.f_Label)
        self.f_Main = QtWidgets.QFrame(LayeAdjuster)
        self.f_Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Main.setObjectName("f_Main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.f_Main)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.f_Main_2 = QtWidgets.QFrame(self.f_Main)
        self.f_Main_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Main_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Main_2.setObjectName("f_Main_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.f_Main_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.f_Main_3 = QtWidgets.QFrame(self.f_Main_2)
        self.f_Main_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Main_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Main_3.setObjectName("f_Main_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.f_Main_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblCurrect_Cadastral_2 = QtWidgets.QLabel(self.f_Main_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lblCurrect_Cadastral_2.setFont(font)
        self.lblCurrect_Cadastral_2.setObjectName("lblCurrect_Cadastral_2")
        self.horizontalLayout_3.addWidget(self.lblCurrect_Cadastral_2)
        self.cmbProjects_Layer = QtWidgets.QComboBox(self.f_Main_3)
        self.cmbProjects_Layer.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmbProjects_Layer.setFont(font)
        self.cmbProjects_Layer.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cmbProjects_Layer.setIconSize(QtCore.QSize(6, 6))
        self.cmbProjects_Layer.setObjectName("cmbProjects_Layer")
        self.cmbProjects_Layer.addItem("")
        self.cmbProjects_Layer.setItemText(0, "")
        self.cmbProjects_Layer.addItem("")
        self.cmbProjects_Layer.setItemText(1, "")
        self.cmbProjects_Layer.addItem("")
        self.cmbProjects_Layer.setItemText(2, "")
        self.cmbProjects_Layer.addItem("")
        self.cmbProjects_Layer.setItemText(3, "")
        self.horizontalLayout_3.addWidget(self.cmbProjects_Layer)
        self.verticalLayout_3.addWidget(self.f_Main_3)
        self.verticalLayout_4.addWidget(self.f_Main_2)
        self.f_Main_1 = QtWidgets.QFrame(self.f_Main)
        self.f_Main_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Main_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Main_1.setObjectName("f_Main_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.f_Main_1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblCurrect_Cadastral = QtWidgets.QLabel(self.f_Main_1)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lblCurrect_Cadastral.setFont(font)
        self.lblCurrect_Cadastral.setObjectName("lblCurrect_Cadastral")
        self.horizontalLayout.addWidget(self.lblCurrect_Cadastral)
        self.cmbPreferred_Project_status = QtWidgets.QComboBox(self.f_Main_1)
        self.cmbPreferred_Project_status.setObjectName("cmbPreferred_Project_status")
        self.horizontalLayout.addWidget(self.cmbPreferred_Project_status)
        self.verticalLayout_4.addWidget(self.f_Main_1)
        self.Projekcts_FolderSetup = QtWidgets.QFrame(self.f_Main)
        self.Projekcts_FolderSetup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Projekcts_FolderSetup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Projekcts_FolderSetup.setObjectName("Projekcts_FolderSetup")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout(self.Projekcts_FolderSetup)
        self.horizontalLayout_62.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_62.setSpacing(10)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.lblProjectsFolder = QtWidgets.QLabel(self.Projekcts_FolderSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblProjectsFolder.setFont(font)
        self.lblProjectsFolder.setObjectName("lblProjectsFolder")
        self.horizontalLayout_62.addWidget(self.lblProjectsFolder)
        spacerItem = QtWidgets.QSpacerItem(370, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_62.addItem(spacerItem)
        self.leProjectsFolder_location = QtWidgets.QLineEdit(self.Projekcts_FolderSetup)
        self.leProjectsFolder_location.setMinimumSize(QtCore.QSize(500, 0))
        self.leProjectsFolder_location.setObjectName("leProjectsFolder_location")
        self.horizontalLayout_62.addWidget(self.leProjectsFolder_location)
        self.verticalLayout_4.addWidget(self.Projekcts_FolderSetup)
        self.Projekcts_FolderSetup_2 = QtWidgets.QFrame(self.f_Main)
        self.Projekcts_FolderSetup_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Projekcts_FolderSetup_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Projekcts_FolderSetup_2.setObjectName("Projekcts_FolderSetup_2")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout(self.Projekcts_FolderSetup_2)
        self.horizontalLayout_63.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_63.setSpacing(10)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.lblProjectsTargetFolder = QtWidgets.QLabel(self.Projekcts_FolderSetup_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblProjectsTargetFolder.setFont(font)
        self.lblProjectsTargetFolder.setObjectName("lblProjectsTargetFolder")
        self.horizontalLayout_63.addWidget(self.lblProjectsTargetFolder)
        spacerItem1 = QtWidgets.QSpacerItem(370, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(spacerItem1)
        self.leProjectsTargetFolder_location = QtWidgets.QLineEdit(self.Projekcts_FolderSetup_2)
        self.leProjectsTargetFolder_location.setMinimumSize(QtCore.QSize(500, 0))
        self.leProjectsTargetFolder_location.setObjectName("leProjectsTargetFolder_location")
        self.horizontalLayout_63.addWidget(self.leProjectsTargetFolder_location)
        self.verticalLayout_4.addWidget(self.Projekcts_FolderSetup_2)
        self.verticalLayout.addWidget(self.f_Main)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.f_Buttons = QtWidgets.QFrame(LayeAdjuster)
        self.f_Buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_Buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_Buttons.setObjectName("f_Buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.f_Buttons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(411, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pbCancel = QtWidgets.QPushButton(self.f_Buttons)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_2.addWidget(self.pbCancel)
        self.pbSave = QtWidgets.QPushButton(self.f_Buttons)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pbSave.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Kalver\\Desktop\\Plugins\\mailabl-qgis\\mailabl-qgis\\config\\confWidgets\\../../icons/Icons_hele/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSave.setIcon(icon)
        self.pbSave.setIconSize(QtCore.QSize(18, 18))
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_2.addWidget(self.pbSave)
        self.verticalLayout.addWidget(self.f_Buttons)

        self.retranslateUi(LayeAdjuster)
        QtCore.QMetaObject.connectSlotsByName(LayeAdjuster)

    def retranslateUi(self, LayeAdjuster):
        _translate = QtCore.QCoreApplication.translate
        LayeAdjuster.setWindowTitle(_translate("LayeAdjuster", "Mailabl projektide eelistused"))
        self.label.setText(_translate("LayeAdjuster", "Projektide seadistused"))
        self.lblCurrect_Cadastral_2.setText(_translate("LayeAdjuster", "Projektide kaardikiht"))
        self.lblCurrect_Cadastral.setText(_translate("LayeAdjuster", "Projekti loetelu eelistused"))
        self.lblProjectsFolder.setText(_translate("LayeAdjuster", "Projekti baaskaust"))
        self.lblProjectsTargetFolder.setText(_translate("LayeAdjuster", "Projekti sihtkaus"))
        self.pbCancel.setText(_translate("LayeAdjuster", "Tühista"))
        self.pbSave.setText(_translate("LayeAdjuster", "Salvesta andmed"))
